### ISSUE TITLE
[BUG] Soul Hacker fusion tool is sometimes one rank off

### ISSUE THREAD

**Issue by Gravitinox** [aqiu384/megaten-fusion-tool#1]
When using the Soul Hackers fusion tool, I've noticed sometimes the result is off by one rank. For example, when looking at Reverse Fusion for Lvl 37 Beast Kaso, it lists Lvl 24 Fairy Silky + Lvl 27 Wilder Jersey Devil. However, this actually produces Lvl 28 Beast Nekomata, since the formula is: floor((24+27)/2)+3 = 28. Now since there is already a Lvl 28 Beast Nekomata, that is the result, the game will not try to look up the rank list to return Lvl 37 Beast Kaso.

I'm guessing the code missed taking into account the floor function in the fusion calculation? Since looking at Beast Kaso's list there are only 3 other mistakes, all with 28.5 as the result if floor wasn't taken into account, but no pairings in the list give a result of Lvl 28 or lower.

**Comment by aqiu384** [comment]
Need to verify which other games use rounding versus which use truncation.
Fixed with 6036152
