### ISSUE TITLE
Incorrect Icon used in Persona 1 Fusion Ingredient List

### ISSUE THREAD

**Issue by Lydonious** [aqiu384/megaten-fusion-tool#10]
The Persona 1 Fusion Lists very conveniently list the fusion icons that the game displays during a Manual Fusion to show the player how skill inheritance will behave on the result demon.

The possible icons in-game are "Right Arrow", "Upper Right Arrow", "Lower Right Arrow", "Circle", and "X". The X icon means it will not be a valid fusion. The Circle means there will be a fusion with no inheritance. And the Arrows mean that there will be a fusion with skill inheritance, with the direction of the arrow describing the inheritance behavior and stat-bonus / stat-penalty.

The Fusion tool as of now uses a "Right Arrow" for when the result would be a "Circle" in-game. It uses an X when it would be a Right Arrow in-game. The diagonal arrows are correctly reflecting the icons the game uses.

I assume that the format of icons in the tool now is a slight error, because it is extremely misleading to use in its current state.

**Comment by aqiu384** [comment]
Fixed with 382d0c
