### ISSUE TITLE
SMT V Fusion Calculator corrections

### ISSUE THREAD

**Issue by GreenMage7** [aqiu384/megaten-fusion-tool#102]
In SMTV, Zeus's Keraunos does not mention that it is a strength-based electric attack. This would be important information for anyone fusing him.

![Untitled](https://user-images.githubusercontent.com/94960528/143209540-e6ebfa5f-8497-4335-832a-1677a0b6605f.png)

Also, the move Arkashic Arts is labeled as heavy damage when it is also listed as severe in game.

Thank you so much for your hard work and time.

**Comment by aqiu384** [comment]
Fixed with db856a5
