### ISSUE TITLE
Using Hayataro in the fusion recepie formula. 

### ISSUE THREAD

**Issue by HeyItsIconic** [aqiu384/megaten-fusion-tool#109]
Hi! I've noticed that when preparing for demons with the Enduring Soul skill the default demon used is Hayataro, which causes a bunch of issues as Hayatark is a late game route exclusive demon. 

Just figured it's better to just by pass him in the fusion recepie generator, since otherwise fusing for enduring soul is near impossible :)

**Comment by aqiu384** [comment]
Fixed with e89083a
