### ISSUE TITLE
SMT5 Compendium Costs Inaccurate

### ISSUE THREAD

**Issue by YoursTrulyMarion** [aqiu384/megaten-fusion-tool#110]
Was looking to finalize my compendium by crosschecking it with the one listed here and none of the costs seem to align with my basic entries. I'm on a new cycle with no Summoner's Hospitality Miracle and my entries are all base level and innate skills only. No additionnal stats either. Everything corresponds except for the summoning costs.

**Comment by aqiu384** [comment]
Fixed with 2af2139

**Comment by YoursTrulyMarion** [comment]
Some prices are off by 1 macca, but otherwise everything is much more accurate. Thanks a lot!
