### ISSUE TITLE
SMT 1: Night Succubus x Yoma Choronzon = Fairy Tam Lin?

### ISSUE THREAD

**Issue by xandris** [aqiu384/megaten-fusion-tool#112]
Hi! Thank you for your app. My partner is playing through SMT 1 and was trying to make Tam Lin. The [reverse fusions](https://aqiu384.github.io/megaten-fusion-tool/smt1/demons/Tam%20Lin/fissions) for Tam Lin suggest it can be made from Night Succubus and Yoma Choronzon, but the actual result is Yoma Kinnara.

[The forward fusions for Night Succubus](https://aqiu384.github.io/megaten-fusion-tool/smt1/demons/Succubus/fusions) claim fusing it with Yoma Choronzon should just yield another Night Succubus, which is inconsistent with the reverse fusions of Fairy Tam Lin.

The [fusion chart](https://aqiu384.github.io/megaten-fusion-tool/smt1/chart) shows "NETH" at the intersection of Yoma and Night. [Atlus's manual for the IOS version](https://atlus.com/smti/manual/021.html) just labels that as a "Special fusion." So I guess this fusion follows different rules.

It seems like the forward and reverse fusions are giving misleading answers because of this "similar race" mechanic, but I'm sure there's something we're missing. Thank you for your time!

**Comment by aqiu384** [comment]
Fixed with [0e8fe16](https://github.com/aqiu384/megaten-fusion-tool/commit/0e8fe1665a62891c8a7028b3c8d2820dfe864175)

**Comment by xandris** [comment]
thank you very much!
