### ISSUE TITLE
Feature request: maximum level input for fusion calculator

### ISSUE THREAD

**Issue by jasyip** [aqiu384/megaten-fusion-tool#115]
I'm playing SMT 5, and it's great to use the fusion calculator for each boss I encounter. However, if I want a demon whose level is less than are equal to mine with selected skills available in lower-level demons, then I sometimes see way higher level demons throughout the chain. There should be an optional input for your current Nahobino level, then the calculator should try its best to make sure there is no demon that goes above that level.

**Comment by aqiu384** [comment]
[0e8fe16](https://github.com/aqiu384/megaten-fusion-tool/commit/0e8fe1665a62891c8a7028b3c8d2820dfe864175)
