### ISSUE TITLE
A way to remove demons of the "Famed" race from the Fusion Recipe tool of SMT IV

### ISSUE THREAD

**Issue by LJJunior** [aqiu384/megaten-fusion-tool#117]
Is there a way to remove demons of the "Famed" race of the Fusion Recipe tool of SMT IV? (the same way you can remove DLC demons from the listings would be great) Since those demons are fusion accident exclusives, sorry for my bad english.

**Comment by aqiu384** [comment]
Fixed with [25dbeb9](https://github.com/aqiu384/megaten-fusion-tool/commit/25dbeb9da38d106f1b212ceb1a12820df141eb8e)
