### ISSUE TITLE
Dx2 some skills are wrong

### ISSUE THREAD

**Issue by guinibir** [aqiu384/megaten-fusion-tool#12]
Kinmamon’s barrier is single target skill not aoe,
Huang Di’s yinlong killer extra effect is 35% curse, not 50% crit

**Comment by aqiu384** [comment]
Confirmed Barrier description is 1 Ally in Japanese as well. Could not find any Japanese info indicating Yinlong Killer causes Curse. Since English Dx2 descriptions are known to have multiple issues, reopen if there is a recording showing Yinlong Killer in action. Closed with 23be789
