### ISSUE TITLE
SH 2 - Special fusion information

### ISSUE THREAD

**Issue by ghed83** [aqiu384/megaten-fusion-tool#120]
The following special fusion information is missing or incomplete for Soul Hackers 2:

- Ardha (Deity) (lvl. 98)
-- Shiva (Fury) + Parvati (Megami)
-- Kurikaya Kokuryur (innate) + Glacial Blast (innate) + Megidolaon (innate) + Deathbound (innate) + Firm Stance (lvl. 99)
- Satan (Tyrant) (lvl. 90)
-- Amon (Tyrant) + Flauros (Fallen) + Dominion (Divine) + Principality (Divine)
- Mara (Tyrant) (lvl. 62)
-- Ananta (Dragon) + Girimekhala (Jaki) + Mishaguji (Vile)
- Masakado (Hero) (lvl. 62)
-- Asura (Fury) + Oyamatsumi (Kishin) + Nue (Wilder) + Xuanwu (Avatar)
- Nemissa (Cyber) (lvl. 60)
-- Titania (Fairy) + Dominion (Divine) + Succubus (Night)
- Zaou-Gongen (Fury) (lvl. 46)
-- Arahabaki (Deity) + Quetzalcoatl (Dragon)
- Armaiti (Herald) (lvl. 43)
-- Vasuki (Drake) + Mithras (Tyrant) + Archangel (Divine)
- Anahita (Megami) (lvl. 28)
-- Sukuna-Hikona (Kishin) + Mermaid (Femme)
- Tzitzimitl (Tyrant) (lvl. 24)
-- Fortuna (Megami) + Sandman (Night) + Gremlin (Jaki)

**Comment by aqiu384** [comment]
Fixed with [e28ddef](https://github.com/aqiu384/megaten-fusion-tool/commit/e28ddef384f870ad327494de15cddad0c185aa01)
