### ISSUE TITLE
SH 2 - Recipe generator skill affinities inheritance

### ISSUE THREAD

**Issue by ghed83** [aqiu384/megaten-fusion-tool#121]
The recipe generator for Soul Hackers 2 does not take into account skill affinities and the impossibility of inherting certain skills.

Example:
1. Set race to "Genma" and demon to "Kurama Tengu"
2. Choose elem "for" and name "Zandyne"

The recipe will suggest a fusion path of:
> Sudama [Zandyne (43)] x Tsuchigumo = Lemon Frost
> Lemon Frost x Hare of Inaba = Dormarth
> Dormarth x Cironnup = Kurama Tengu

However Lemon Frost cannot inherit force abilities.

**Comment by Kishinsama42** [comment]
I've experienced  this as well.  

Example 
Wanting to pass Agidyne to Skadi requires Surt and Rakshasa to fusion to Yamato no Orochi. Yamato plus Dakini creates Skadi, but cannot inherent fire skills

**Comment by dsantiago** [comment]
Yeah, too bad the Recipe generator is almost useless as it always checks fusions fthat cannot inherit skills.

**Comment by aqiu384** [comment]
Fixed with [8c49923](https://github.com/aqiu384/megaten-fusion-tool/commit/8c49923cf2167a4f6a8b7683c0475fbfafe1b593)
