### ISSUE TITLE
P5R - Wrong skill on Shadow Lvl 52 Final Assessor (Norn)

### ISSUE THREAD

**Issue by Armetz** [aqiu384/megaten-fusion-tool#122]
The fusion tool displays Final Assessor to possess Diarahan, whereas she possesses Diarama as a Shadow.

**Comment by aqiu384** [comment]
Fixed with [e28ddef](https://github.com/aqiu384/megaten-fusion-tool/commit/e28ddef384f870ad327494de15cddad0c185aa01)
