### ISSUE TITLE
Stats for DLC personas in Persona Q are wrong.

### ISSUE THREAD

**Issue by Oldamar999** [aqiu384/megaten-fusion-tool#123]
the DLC personas have stats listed as far higher than they should be, all having an extra random digit added at the end for whatever reason.
Kaguya: +724 HP and +379 SP, real stats are +72 and + 37
Orpheus Telos: +1255 HP and +337 SP, actually +125 and +33
Thanatos: +1860 HP and +546 SP, actually +186 and +54
Magatsu Izanagi: +2200 HP and +600 SP, actually +220 and +60

**Comment by aqiu384** [comment]
Fixed with [8c49923](https://github.com/aqiu384/megaten-fusion-tool/commit/8c49923cf2167a4f6a8b7683c0475fbfafe1b593)
