### ISSUE TITLE
Any plans to include skill multipliers for p5r like for p4g?

### ISSUE THREAD

**Issue by SoraRoxasVentus** [aqiu384/megaten-fusion-tool#125]
I really love the tool but one thing that would help improve it a lot for me are the actual multipliers for the persona 5 skills, other games such as smt5 or p4g have them so it feels a bit of a wasted opportunity to not also have them for persona 5

**Comment by aqiu384** [comment]
Fixed with [3a565fb](https://github.com/aqiu384/megaten-fusion-tool/commit/3a565fb64d2f2c8f445caf1c0191e94b00443da3)
