### ISSUE TITLE
Small mistake regarding rebellion blade down multiplier

### ISSUE THREAD

**Issue by SoraRoxasVentus** [aqiu384/megaten-fusion-tool#129]
let me preface by saying that the new p5r update with the skill multipliers is incredible! There's just one small thing wrong that I found so far, rebellion blade (akechi's exclusive skill) actually replaces the downed bonus of x1.25 with a x2.5 bonus as can be seen in this video (https://youtu.be/hLtQsLiuyws?t=69) 1100~ x 2.5 = 2750, accounting for the 5% variance in damage you can see how that 2798 came about. However on the site it's listed as "Dmg x1.5 against downed foe", I suggest changing it to "Raises downed multiplier to x2.5"

**Comment by aqiu384** [comment]
Fixed with [60f6a6e](https://github.com/aqiu384/megaten-fusion-tool/commit/60f6a6ee390f956a06fe4c26e2ffd2f1c1e9a737)
