### ISSUE TITLE
update the password generator 

### ISSUE THREAD

**Issue by deletingthissoon** [aqiu384/megaten-fusion-tool#13]
im testing the passwords generator with smt: strange journey redux and they all came up invalid so please fix that thank you.

**Comment by aqiu384** [comment]
Ensure you are inputting the correct password (0 vs O, l vs 1), are not attaching unique skills (shown in red) to any demon except their original, and try different mask bytes. If problems persist please list the invalid passwords and screenshot the moment they are entered.
