### ISSUE TITLE
Persona 5 Royal calculation off when fusing two of the same Arcana.

### ISSUE THREAD

**Issue by cw171** [aqiu384/megaten-fusion-tool#130]
From what I understand if the average of the base levels of two Personas within the same Arcana is .5 or 1 below a Persona in that Arcana, the result should be that Persona, but the Persona 5 Royal calculator is giving the next Persona down from there, as if either "<" is being used rather than "<=" or the .5/1 isn't being added.

Examples:

Average of Base Levels of:
- Arsene (1) and Izanagi (20): 10.5, should round up to 11 giving Orpheus F, instead goes down to Obariyon (8).
- Cait Sith (5) and Choronzon (28): 16.5 should round up to 17 giving Nekomata, instead goes down to Jack Frost (11).
- Onmoraki (12) and Black Ooze (18): 15, should increase to 16 giving Kaguya, instead goes down to Succubus.

I've checked these in-game as well as on a different calculator.

**Comment by aqiu384** [comment]
Fixed with [60f6a6e](https://github.com/aqiu384/megaten-fusion-tool/commit/60f6a6ee390f956a06fe4c26e2ffd2f1c1e9a737)
