### ISSUE TITLE
Persona 5 Royal Passive Skill Magic Ability Missing

### ISSUE THREAD

**Issue by zenki81** [aqiu384/megaten-fusion-tool#134]
Hi,

thanks for the awesome work! I was using the persona 5 Royal recipe generator (https://aqiu384.github.io/megaten-fusion-tool/p5r/recipes) and noticed that the passive skill Magic Ability is not in the list. Are you able to include it in?

Appreciate your hard work and effort, thanks!
![FC49AF4F-3AFE-4FE6-BB62-61C2EA18D1BE](https://user-images.githubusercontent.com/25135607/204072950-7d7f0069-bfe3-43dc-9fb6-1e808c9e7aee.jpeg)

**Comment by aqiu384** [comment]
Magic Ability is network fusion only.
