### ISSUE TITLE
Shin Megami Tensei 1 Dark Fusions

### ISSUE THREAD

**Issue by fgw3** [aqiu384/megaten-fusion-tool#137]
For Normal fusion, if the Dark demon's level is equal to or greater than the Non-Dark demon's level, and their total level is a multiple of 3, the Dark demon will rank up. If the Non-Dark demon's level is greater than the Dark demon's level, and their total level is a multiple of 7, the Non-Dark demon will rank up.

Tyrant Dagon (LV 74) + Night Imp (LV 7) = Total level 81, 81 mod 3 = 0, so Tyrant Dagon ranks up to Tyrant Bael.

Element Undine (LV 30) + Spirit Pisaca (LV 19) = Total level 49, 49 mod 7 = 0, so Element Undine ranks up to Element Salamander.

**Comment by aqiu384** [comment]
Fixed with [5759ed5](https://github.com/aqiu384/megaten-fusion-tool/commit/5759ed55b354e5bcd59816c3d4cac5afea096dc6)
