### ISSUE TITLE
P5R recipe generator feature requested: factored number of parent skills to inherited skill

### ISSUE THREAD

**Issue by meanssaddles** [aqiu384/megaten-fusion-tool#138]
for example if i want onmoraki (max level 13) with 4 inherited skills (first level elec/ice/wind and life drain) recipe generator will give me a result like this: https://media.discordapp.net/attachments/813042041739149363/1051047108733587466/Screenshot_20221210_150127_org.mozilla.fenix_1.jpg 

but if i go ahead and fusion exactly with that (at base level, since they don't specific ingredients level), the results will be i won't get enough skill from silky x obariyon to inherited 4 skills (which requires a total of 13 skill from both parents) and i need to do them all by hand (and add extra steps or even change mon since base number of skill on some mons are lacking) which is time consuming and it is what recipe generator suppose to do https://media.discordapp.net/attachments/813042041739149363/1051049002050793512/IMG_20221210_024718.jpg

**Comment by aqiu384** [comment]
Fixed with [5759ed5](https://github.com/aqiu384/megaten-fusion-tool/commit/5759ed55b354e5bcd59816c3d4cac5afea096dc6)

**Comment by meanssaddles** [comment]
i don't see any change compared to previous image (in fact it's harder to use since now there's a list of monster alphabetically but not their level) https://media.discordapp.net/attachments/813042041739149363/1061004732434481232/1000002584.jpg
