### ISSUE TITLE
(P3 FES The Journey + P3P) Questioning the lack of tri-fusion recipes for Orpheus Telos.

### ISSUE THREAD

**Issue by BothDoorsCares** [aqiu384/megaten-fusion-tool#139]
I would understand not using tri-fusion for FES since it would be inferior to hexagonal fusion from a skill inheritance perspective but it would definitely be helpful in P3P where skill cards exists. Although I would imagine it would be quite a long list from what I can understand of how P3 fusion works.

**Comment by aqiu384** [comment]
Fixed with [5759ed5](https://github.com/aqiu384/megaten-fusion-tool/commit/5759ed55b354e5bcd59816c3d4cac5afea096dc6)
