### ISSUE TITLE
Not an issue!

### ISSUE THREAD

**Issue by KamilProgramista** [aqiu384/megaten-fusion-tool#14]
HI!

I couldn't find a way to contact you as it seems that this site doesnt support PM's, so i thought I will write here instead :). I'm learning programming by following the cs50 course and learning python at the moment. I would like to do something similar to your demon calculator in the future as a way to practice and learn more things. I'm wondering what technologies are needed to do something as complex as your app. Python + JavaScript would be enough? How did you get all the demon info? Did you have to type everything on your own? Where did you get all the icons? I don't know if you can reply me here, so you could send a mail at 360dante@gmail.com. Btw. thank you for what you did, your calculator really helped me when i played smt4 and smt4:a :).

**Comment by aqiu384** [comment]
> Python + JavaScript would be enough?

Yes

> How did you get all the demon info?

https://aqiu384.github.io/megaten-fusion-tool/home

> Did you have to type everything on your own?

No

> Where did you get all the icons?

http://megamitensei.wikia.com
