### ISSUE TITLE
(P5R) Feature Request

### ISSUE THREAD

**Issue by RobertoJKN** [aqiu384/megaten-fusion-tool#140]
![image](https://user-images.githubusercontent.com/32022277/209268892-60bb1a77-80a2-4d20-9418-71af519351a3.png)

Is it possible to add more customization to the recipe generator? For instance, I want to fuse a Clotho with a bunch of support skills, I'm even willing to do a bunch of fusions to get there, but there's currently no way to remove personas from the calculations. 

In this specific scenario, I wanted to limit the ingredient personas' levels to 27 (my current level; don't want to use personas that have a higher base level than my level), I also can't get a level 26 Orthrus, as I get no bonus XP from Hanged fusions (and I'm not leveling an Orthrus from 21 to 26).

You could also add an option to use skill cards (and then show how to get those skill cards in the recipe generator, but this is a minor request).

I could go more in depth, but it would make this post too long, so if any of my suggestions seem good, I can elaborate further.
Thank you.

**Comment by aqiu384** [comment]
Fixed with [5759ed5](https://github.com/aqiu384/megaten-fusion-tool/commit/5759ed55b354e5bcd59816c3d4cac5afea096dc6)
