### ISSUE TITLE
p5r recipe generator - missing treasure demon in skill searcher

### ISSUE THREAD

**Issue by meanssaddles** [aqiu384/megaten-fusion-tool#143]
also it would be nice if max level affected skill searcher or recipe too (currently it does nothing, not sure a bug or intended, but i don't see any different whether i set it to level 10 or level 99)

**Comment by aqiu384** [comment]
Fixed with [a0315b3](https://github.com/aqiu384/megaten-fusion-tool/commit/a0315b335009e8e8e1c998f4c52a3f91660032e3)
