### ISSUE TITLE
recipe generator features request 

### ISSUE THREAD

**Issue by meanssaddles** [aqiu384/megaten-fusion-tool#144]
not sure how feasible to implement but I'll just get the idea out:

1. a level limit would be useful (previously removed, probably due to not functional?) - let's say i choose level 50 then the recipe generator wouldn't use anything level more than 50 in the fusion recipe

2. "any" choice for Target: Race, Name and Include Ingredients: Ingredient box to act as wildcard would be really useful if level limit can be implement. since user won't need to look up a starter persona and can just put in the skill they want and recipe generator will (hopefully) generated the one that fits all the criteria, and if they want to specific target persona (or race) or ingredients they can still do

**Comment by aqiu384** [comment]
Fixed with [92a3d81](https://github.com/aqiu384/megaten-fusion-tool/commit/92a3d814789a010db3acd567f6acadfe8131c1d4)
