### ISSUE TITLE
Skill Data for P3 FES/Portable

### ISSUE THREAD

**Issue by yukiyoneko** [aqiu384/megaten-fusion-tool#145]
Hi, I have some edits to skill data for Persona 3 FES and Portable, I've attached here edits if I've done them correctly, if not, I've included 2 links for skill data taken from the games

https://docs.google.com/spreadsheets/d/1F2RrgcxTwZ-wvp7HKu1N6ScftEk_GiXbwp_sc7ZK1t4/edit?usp=sharing - FES
https://docs.google.com/spreadsheets/d/14wetkLNjJgc-cP36yYXmexUMEBd8kcvejE-VGQMM_7Q/edit?usp=sharing - Portable

I edited fes skill data to match, and if a skill wasn't in there, it was edited in van skill data, dunno if that works.

[fes-skill-data.txt](https://github.com/aqiu384/megaten-fusion-tool/files/10461654/fes-skill-data.txt)
[p3p-skill-data.txt](https://github.com/aqiu384/megaten-fusion-tool/files/10461649/p3p-skill-data.txt)
[van-skill-data.txt](https://github.com/aqiu384/megaten-fusion-tool/files/10461651/van-skill-data.txt)

Party members have a different skill set in FES compared to Portable, here are the ones for FES, the ones listed normally are Portable versions.
[party-data-fes.txt](https://github.com/aqiu384/megaten-fusion-tool/files/10461652/party-data-fes.txt)

Special Note: in P3P all aoe kaja skills are 16 sp, not 12, wasn't sure if it would work to add that in so I didn't include it, as well as the effectiveness of buffs being 1.33x instead of 1.25x -- these are the only skill changes besides newly available skills in portable afaik

Additionally, fusion skills are % sp if that can be changed

If the edits don't work, here's a list of skills in alphabetical order that have a different effect than listed
[skill-edits.txt](https://github.com/aqiu384/megaten-fusion-tool/files/10461804/skill-edits.txt)

Feel free to use the attached skill data sheets, all data was taken directly from the game or determined through testing (buffs, ailment boosts, counters, charges, damage bonuses, break skills, etc.)

Also, just curious, is it intentional that skills don't have accuracy attached? I saw them included in the data.jsons but not on the main pages

Thanks for your time

**Comment by aqiu384** [comment]
Fixed with [92a3d81](https://github.com/aqiu384/megaten-fusion-tool/commit/92a3d814789a010db3acd567f6acadfe8131c1d4)
