### ISSUE TITLE
Potentially Misleading Base Power of the Skills (P5R)

### ISSUE THREAD

**Issue by IceTMDAbss** [aqiu384/megaten-fusion-tool#147]
The displayed Base Power of the different skills are raw, but the game **doesn't work this way since it's based on √x instead**.

The obvious problem is that it can be confusing at best and even misleading for those ignoring this fact since **the damage difference can be completely different**, even more with multi-hit skills. 

1. **Severe ST vs. Heavy ST Basic Elemental Spells**

- Raw Base Power: 
     -_Atomic Flare_: 200
     -_Freidyne_: 160
     -Supposed damage difference: 200÷160 = 1.25
     -**CONCLUSION**: **_Atomic Flare_ is supposedly 25% stronger than _Freidyne_**.
 
Which is far from being the case in-game, the damage difference is way lower.

- √x Formula:
     -_Atomic Flare_: ~14.14
     -_Freidyne_: ~12.65
     -Supposed damage difference: 14.14÷12.65 ≃ 1.118
     -**CONCLUSION**: **_Atomic Flare_ is supposedly ~11%-12% stronger than _Freidyne_**.
   
Which is very close to the results you get in-game.

2. **Ultimate Physical Skills Comparison**

- Raw Base Power:
     -_God's Hand_: 800
     -_Hassou Tobi_: 320 (40x8)
     -Supposed damage difference: 800÷320 = 2.5 
     -**CONCLUSION: _God's Hand_ is supposedly x2.5 stronger than _Hassou Tobi_**.

- √x Formula: 
     -_God's Hand_: ~28.28
     -_Hassou Tobi_: ~50.6 (√40x8)
     -Supposed damage difference: 50.6÷28.28 ≃ 1.79
     -**CONCLUSION: _Hassou Tobi_ is supposedly ~79% stronger than _God's Hand_**. 

In one of my testings, _Hassou Tobi_ was dealing roughly ~75%-80% more than _God's Hand_ against the _Reaper_ (small sample). 

3. **Potential solutions** 

The most valid solutions in my eyes would be: 
- Include the √ symbol before any Base Power. 
-Update the entire section with the true BP based on the √x formula.
-Get back to the game's description system with Severe/Heavy/Medium/Light/Miniscule tiering. Although it's not as accurate, at least it's not misleading.

_EDIT: I also just noticed that for the Ailments coming from Physical skills, the rate isn't mentioned anymore. Might be good to actually update this as Terror Claw and Bloodbath don't have the same Fear rate for example._

**Comment by aqiu384** [comment]
Fixed with [173b270](https://github.com/aqiu384/megaten-fusion-tool/commit/173b270b278b691f6e806804e1cb4406ea61730b)
