### ISSUE TITLE
(P3F) Alilat Special Fusion Condition

### ISSUE THREAD

**Issue by Armetz** [aqiu384/megaten-fusion-tool#148]
A **Special Fusion Condition** should be added: _"Empress Rank 10"_
See the third paragraph on [Mitsuru's SL page](https://megamitensei.fandom.com/wiki/Social_Link/Mitsuru_Kirijo)

**Comment by aqiu384** [comment]
Fixed with [173b270](https://github.com/aqiu384/megaten-fusion-tool/commit/173b270b278b691f6e806804e1cb4406ea61730b)
