### ISSUE TITLE
P4G Firm Stance is Rank 5

### ISSUE THREAD

**Issue by Crabberd** [aqiu384/megaten-fusion-tool#155]
Firm stance is rank 5, not rank 7.

![CD4D8504-4DFF-48B2-87E3-99CCBF60A403](https://user-images.githubusercontent.com/132855274/236705579-f4df29ec-a317-4741-b684-2d449da37081.jpeg)

**Comment by aqiu384** [comment]
Fixed with [7f71fba](https://github.com/aqiu384/megaten-fusion-tool/commit/7f71fba838bcb0a308e834bbdd9ec2e0d325988b)
