### ISSUE TITLE
[REQUEST] Persona 2 Innocent Sin & Eternal Punishment additions

### ISSUE THREAD

**Issue by yukiyoneko** [aqiu384/megaten-fusion-tool#156]
As title says, a request for P2IS and P2EP to be included in a similar fashion to Megami Ibunroku Persona with SP cost, rank growth, compatibility, return items, and mutations in addition to standard info. I understand the games don't actually have fusion, but it'd be a good resource to have regardless.

**Comment by aqiu384** [comment]
Fixed with b192b392ac52a515c59d45bed80d1dc3977aff51
