### ISSUE TITLE
SMT III Sonic Wave and skill description

### ISSUE THREAD

**Issue by Matternik** [aqiu384/megaten-fusion-tool#157]
The description of Sonic Wave in SMT III says it inflicts stun, but it actually inflicts panic.
Also, the descriptions of Iron Claw, Dark Sword, Hell Fang and Stasis Blade say “Hight crit” instead of “High crit” (Not sure if this was somehow intentional thought)

**Comment by aqiu384** [comment]
Fixed with [c85a789](https://github.com/aqiu384/megaten-fusion-tool/commit/c85a7898016236802ee3e0d08202be8c3ed774ee)
