### ISSUE TITLE
SMT4 Demon Stat Error

### ISSUE THREAD

**Issue by FlameNoir** [aqiu384/megaten-fusion-tool#16]
The Demon "Hitokoto-Nushi" is listed as having "Dex: 68" and "Mag: 53," but this is incorrect. As I observed in the game, the stats are actually reversed--the Demon has a base 53 Dex and a base 68 Mag. A minor error, yes, but I nearly fused demons in preparation of creating a gun-based demon before realizing that in fact his stats are magic-oriented.

**Comment by aqiu384** [comment]
Fixed with 182325c
