### ISSUE TITLE
Adding "morphable" status to FES(and presumably, OG/portable/4) skills?

### ISSUE THREAD

**Issue by TheSasaWorker** [aqiu384/megaten-fusion-tool#160]
I was initially going to mention skill ranks being in the wrong order for magic skills(agi<maragi<agilao<maragion<agidyne<maragidyne), but thankfully that was fixed somewhat recently. That said, this is more of a suggestion.
I'm sure everybody knows about skill "morphs", or mutations, or whatever you want to call them. What I'm suggesting is adding an extra list component, or a simple asterisk, or some kind of symbol next to each skill denoting whether it is possible to morph or not. 

![image](https://github.com/aqiu384/megaten-fusion-tool/assets/43584270/8af477ad-437f-4d8e-a0dc-cd68149aaa21)

To further explain what I'm referring to, Invigorate 1-2-3 are all morphable into higher rank skills (eg Invig 1 can become Invig 2, Null Charm or whatever else; Invig 2 can become Repel Fire, Endure what have you and so on). On the other hand, some skills are simply impossible to morph, such as the AOE magic spells(mabufu, mazionga, magarudyne), a lot of phys skills, some weird passives(autos, evades) and so on. Either way, the point is that it would be great to be made aware of what can mutate and what can't, if only for the sake of making this obscure mechanic easier to come across.

The Japanese guide book(game guide? whatever it is) already has this exact feature, but the main issue frankly is that I don't know JP, nor is it possible to OCR the text there. The second column describes morph-ability as far as my knowledge goes. I could be wrong on that, but design & functionality-wise I am hoping for something like this.

 https://imgur.com/a/rPI3i

Anyways, if need be I can help with testing the morph-ability of skills. I already know a good chunk of them by heart, so it shouldn't take long to figure out the others. What I would do is just add something next to each skill's rank, like * for the sake of avoiding clutter, or otherwise [N] for non-morphables and [M] for morphables if going for something more visible. Here's an example I made in 30 seconds: 

![image](https://github.com/aqiu384/megaten-fusion-tool/assets/43584270/fbf2b8a0-9951-45f9-b605-fac133db4215)

Alternatively, instead of explaining what the letters mean by hovering over them, it may look cleaner to have it so you can hover the Rank column for an explanation instead.

**Comment by aqiu384** [comment]
Fixed with 8680ce2
