### ISSUE TITLE
Arsene can't select Phys and Gun in "Elem" line

### ISSUE THREAD

**Issue by Mackeryayyy** [aqiu384/megaten-fusion-tool#161]
So I try to build some gun build for arsene then I found out that It don't have any selection for phys and gun in the "elem" line, please add them in
![image](https://github.com/aqiu384/megaten-fusion-tool/assets/90702963/2312cdb9-dd6d-4923-9ca0-d9ee99dbce6f)

**Comment by aqiu384** [comment]
Arsene cannot inherit phys or gun skills. They must be skill carded.
