### ISSUE TITLE
[SH2] Recipe generator passive skills list incomplete?

### ISSUE THREAD

**Issue by alichaudry** [aqiu384/megaten-fusion-tool#163]
I counted 48 passive element skills in the sh2 recipe generator but 66 passive element skills in sh2's skill-data.json. Why are some of these skills being filtered out?

**Comment by aqiu384** [comment]
Fixed with [aeecece](https://github.com/aqiu384/megaten-fusion-tool/commit/aeecece652576052d21e3852c3f6a926ca7fbe7c)

**Comment by alichaudry** [comment]
Awesome!

Out of curiosity, this was broken because some of those skills didn't have a `rank` associated with them, and just fills it in w/ a generic `elemCount / 10` when that's the case? I'm not sure I understand the logic of what `elemCount` is even tracking, and why it's starting from 9 now and not 0 like before.
