### ISSUE TITLE
P5R Kodama learned skill switched

### ISSUE THREAD

**Issue by Blank812** [aqiu384/megaten-fusion-tool#164]
Kodama skill unlock order should be
Garu
Rakunda
Psi
Evil Touch
Fear Boost (switched)
Tarukaja (switched)
Resist Fear
![image](https://github.com/aqiu384/megaten-fusion-tool/assets/122515894/26a80121-0188-4fd8-a002-f40e0a021f9c)
![image](https://github.com/aqiu384/megaten-fusion-tool/assets/122515894/86ebffcb-9c03-4b39-99e1-962107d1f0a8)

**Comment by aqiu384** [comment]
Fixed with [aeecece](https://github.com/aqiu384/megaten-fusion-tool/commit/aeecece652576052d21e3852c3f6a926ca7fbe7c)
