### ISSUE TITLE
SMT V Healing Skills Boost % Clarification

### ISSUE THREAD

**Issue by Matternik** [aqiu384/megaten-fusion-tool#165]
Could there be clarification in SMT V's help section about the boost % on healing moves? I have no clue on what that means and I didn't find any mention about it online.

**Comment by aqiu384** [comment]
Fixed with [aeecece](https://github.com/aqiu384/megaten-fusion-tool/commit/aeecece652576052d21e3852c3f6a926ca7fbe7c)
