### ISSUE TITLE
P5R Genbu learned skill switched

### ISSUE THREAD

**Issue by Blank812** [aqiu384/megaten-fusion-tool#166]
Genbu skill unlock order should be
Bufu
Rakunda
Patra
Resist Forget (switched)
Mabufu (switched)
Defense Master

*stats on wiki also wrong so i provide my own screenshot
*ignore the zio skill on the screenshot because the skill came from inheritance
![image](https://github.com/aqiu384/megaten-fusion-tool/assets/122515894/57e893a8-8339-4bc4-9d6a-8113e7e03b6f)
![image](https://github.com/aqiu384/megaten-fusion-tool/assets/122515894/1e3b57df-fd4d-4c4c-9207-7021df222297)

**Comment by aqiu384** [comment]
Fixed with [aeecece](https://github.com/aqiu384/megaten-fusion-tool/commit/aeecece652576052d21e3852c3f6a926ca7fbe7c)
