### ISSUE TITLE
[P5R] Recipe Generator suggests Personas which cannot inherit wanted skills

### ISSUE THREAD

**Issue by tiggypuff** [aqiu384/megaten-fusion-tool#167]
For example, when setting "Agilao" and "Bufula" as desired skills for a Take-Minakata (Hanged Arcana) with Orthrus and Sui-Ki as source for these skills, the Recipe Generator suggests to create Jikokuten as an intermediate Persona with Agilao and Bufula. However, Jikokuten cannot inherit elemental skills, and therefore is not suitable as an intermediate step.

**Comment by aqiu384** [comment]
Fixed with [8c02007](https://github.com/aqiu384/megaten-fusion-tool/commit/8c02007a18b357f06636a6bded18f047820efc55)
