### ISSUE TITLE
Persona 3/4 Inheritance Percentages

### ISSUE THREAD

**Issue by yukiyoneko** [aqiu384/megaten-fusion-tool#168]
Hi, I don't see sources linked that reference the percentage biases or inheritance types for Persona 3 and 4 on the help page or in the other issues raised here. Do you happen to still have the links for these? If not any ideas on where they were found? (EN/JP wikis?) If found could these be linked on the help page? They appear to be correct, just don't know where the info came from. Thanks!

**Comment by aqiu384** [comment]
Both were taken from the official guide books.
