### ISSUE TITLE
(SJ Ds) Sabbatma and Invitation is Missing in Generator

### ISSUE THREAD

**Issue by yadifacta** [aqiu384/megaten-fusion-tool#169]
There are a bit issue on Strange Journey (DS) generator 

Sabbatma and Invitation skills are unavailable to other demons on generators, its only available when i pick Brute Ongyo-ki and its not on any skill category. I remember, They were on Recovery (rec) but aren't there anymore.

Also Jihad skill name change to Antichthon despite its DS not 3ds Redux version. So, i think its kinda confusing for those who hasn't play its 3ds version

Thanks

**Comment by aqiu384** [comment]
Fixed with [dc1f38f](https://github.com/aqiu384/megaten-fusion-tool/commit/dc1f38fb1f32bfd735c2b741b4b1663e9ff6e5a5)
