### ISSUE TITLE
SMTIV: Orochi is Weak to the Bind ailment.

### ISSUE THREAD

**Issue by FlameNoir** [aqiu384/megaten-fusion-tool#17]
As title. He can be encountered in the wild in Infernal Tokyo Camp Ichigaya on the lower floors, and he is weak vs. Shibaboo/Bind Voice. 

According to the wiki he is also weak to Poison/Panic/Sleep, but as I do not use those ailments I cannot personally confirm this.

**Comment by aqiu384** [comment]
Fixed with f5a09ba
