### ISSUE TITLE
P5R Persona "Power" doesn't have a gun weakness.

### ISSUE THREAD

**Issue by Kimsewon93** [aqiu384/megaten-fusion-tool#170]
![20230920150652_1](https://github.com/aqiu384/megaten-fusion-tool/assets/145542627/c77379bd-4cc9-4afe-aee3-f0d53e8369a6)

Sorry to use Korean version, but you can see it only has curse weakness. No gun weakness in Royal version.

**Comment by aqiu384** [comment]
Fixed with [6f0789b](https://github.com/aqiu384/megaten-fusion-tool/commit/6f0789b0456a27057fd90e82acdc8aa837783140)
