### ISSUE TITLE
(P3P) Vorpal Blade being listed as non-inheritable when it is + Weapons Master passive not being present in the list of skills

### ISSUE THREAD

**Issue by BothDoorsCares** [aqiu384/megaten-fusion-tool#171]
I believe that this is a mistake, as Vorpal Blade became inheritable again when jumping from FES to P3P. It is definitely an odd decision to make it non-inheritable when jumping from the Original to FES in the first place. 

![Screenshot (1464)](https://github.com/aqiu384/megaten-fusion-tool/assets/121027561/bf122241-4e19-47a7-8e70-0d80c0f2b633)

As for the Weapons Master passives, they seem to have replaced every persona with the older passives with this. And it is obtainable via Skill Card as a reward for rescuing a person nearing endgame (I believe November but I am not sure). So essentially, Thanatos/Siegfried/Thor/Seitein Taisei/Cybele/Melchizedek. Caesar and Kala-Nemi keeps theirs though. So only those two retains the old passives.

(Edit) I forgot to mention that Weapons Master is non-inheritable.

**Comment by aqiu384** [comment]
Fixed with [db7ec54](https://github.com/aqiu384/megaten-fusion-tool/commit/db7ec54138096052cbafe1100bd1c87eb3cdeaae)
