### ISSUE TITLE
SMT V: Omagatoki Free Incorrect Effect Description 

### ISSUE THREAD

**Issue by bob2795** [aqiu384/megaten-fusion-tool#172]
Omagatoki Free’s description is “All attacks will cost 1 MP for 1 turn”, It makes all skills cost 1 MP not just attacks.
 
Here is some footage of it being used: https://youtu.be/T06d_3fZ_S0?si=C7yraawx3Dpgk0pT&t=600

**Comment by aqiu384** [comment]
Fixed with [db7ec54](https://github.com/aqiu384/megaten-fusion-tool/commit/db7ec54138096052cbafe1100bd1c87eb3cdeaae)
