### ISSUE TITLE
[P5R] Nuke Wall is not listed in P5R's Skill List page.

### ISSUE THREAD

**Issue by Zrego** [aqiu384/megaten-fusion-tool#173]
Nuke Wall is not obtainable from any Persona skill trees and Skill Cards. The only way to obtain it legitimately is by mutating a skill during Fusion Alarms. I noticed that Concealment and Taunting Aura are listed as mutation only skill, but for some reason Nuke Wall is not. Here's an evidence of a successful Nuke Wall mutation:
![image](https://github.com/aqiu384/megaten-fusion-tool/assets/37297739/61fba357-fd6c-4f4a-946e-0aa92f748d04)

**Comment by aqiu384** [comment]
Fixed with [11056e6](https://github.com/aqiu384/megaten-fusion-tool/commit/11056e6d34c9691bf0da70fa2704ab9b5ca701bf)
