### ISSUE TITLE
Japanese character used for resist is incorrect

### ISSUE THREAD

**Issue by benedictleejh** [aqiu384/megaten-fusion-tool#174]
In both SMT and Persona, the Japanese character used for resist is 耐, not 強.

Screenshots:
SMT4:
http://img-cdn.jg.jugem.jp/a93/1461316/20130805_806250.jpg, from http://blog.get-ready.org/?eid=900850

SMT4F:
https://livedoor.blogimg.jp/puriyan/imgs/5/4/54cfdd69.jpg, from http://blog.livedoor.jp/puriyan/archives/51766120.html

SMT5:
https://img.altema.jp/megaten5/uploads/2021/11/2021y11m12d_0214151909.jpg, from https://altema.jp/megaten5/rugarukouryaku

P5:
https://www.youtube.com/watch?v=u35j74wpuYQ, first frame

**Comment by aqiu384** [comment]
Fixed with 8a055df
