### ISSUE TITLE
(Vanilla Persona 3) Vorpal Blade has 2x damage bonus from great status. not 1.5x + (P3P) Vorpal Blade's description is reverted to the written Vanilla P3 description after being labeled as inheritable.

### ISSUE THREAD

**Issue by BothDoorsCares** [aqiu384/megaten-fusion-tool#175]
I checked the claim of Vanilla P3's Vorpal Blade being 1.5x and saw that it is bogus. It is 2x, like the other versions.

Normal Status:
![Screenshot (12)](https://github.com/aqiu384/megaten-fusion-tool/assets/121027561/a8b282ac-0b2b-4012-bbb3-b3599e95d0dd)

Great Status:
![Screenshot (13)](https://github.com/aqiu384/megaten-fusion-tool/assets/121027561/78ddb246-d64d-43b1-aded-512c2f245855)

As for its effect in P3P, 500 base, 5% crit chance and 2x Great Status bonus like how it was written before is correct. That could have been an oversight to copy the Vanilla P3 description in the calculator when it was previously changed as inheritable last time.

**Comment by aqiu384** [comment]
Fixed with [ed7732b](https://github.com/aqiu384/megaten-fusion-tool/commit/ed7732bdd71fc6d4e190fa694337423cabd477ca)
