### ISSUE TITLE
(SMT4A) Growing Hate is stronger vs Light resistance + Power values

### ISSUE THREAD

**Issue by SpookiestSpooks** [aqiu384/megaten-fusion-tool#180]
The calculator lists Growing Hate as being "stronger vs Dark resistance", but the in-game description states that Light resistance affects power. Through practical testing, its power is much higher against Resist/Null/Repel/Drain but significantly lower against Weakness.

By the way, I've datamined the game for its power values and they can be found on this list: https://megatenwiki.com/wiki/Skills_in_Shin_Megami_Tensei_IV:_Apocalypse

**Comment by aqiu384** [comment]
Fixed with 1151013
