### ISSUE TITLE
Skill Data for P3 Remake

### ISSUE THREAD

**Issue by yukiyoneko** [aqiu384/megaten-fusion-tool#181]
Hi! I know the page is still a WIP, but here's some data sheets for the game. Attached is a json containing raw skill data and a json with all skill names, but I'll also include a google sheets since that may make it easier to line up skills
https://docs.google.com/spreadsheets/d/11Mlfc_Oi3JU-16jtoNygCntJyKGVl-QWxB_Kttag9yc/edit?usp=sharing

[DatSkillNormalDataAsset.json](https://github.com/aqiu384/megaten-fusion-tool/files/14154463/DatSkillNormalDataAsset.json)
[DatSkillDataAsset.json](https://github.com/aqiu384/megaten-fusion-tool/files/14154464/DatSkillDataAsset.json)
[DatSkillNameDataAsset.json](https://github.com/aqiu384/megaten-fusion-tool/files/14154465/DatSkillNameDataAsset.json)

**Comment by aqiu384** [comment]
Fixed with [66d21db](https://github.com/aqiu384/megaten-fusion-tool/commit/66d21db0b5d59c703827930faea058a4471ef4f4)
