### ISSUE TITLE
P3R Recipe Generator Using Teammate Exclusive Personas

### ISSUE THREAD

**Issue by Dahbestcod** [aqiu384/megaten-fusion-tool#182]
The P3R recipe generator's default ingredient for a skill is the lowest leveled persona which learns it. Sometimes, this is your teammates' personas, resulting in no possible generated chain. Could you exclude those personas from the generator? The issue can be sidestepped by simply picking the next persona in the list, but it was definitely confusing trying to figure what was going wrong at first.

**Comment by aqiu384** [comment]
Fixed with [8aa87af](https://github.com/aqiu384/megaten-fusion-tool/commit/8aa87af1a5ce6ae0e833f7cbec7404f27b201d80)
