### ISSUE TITLE
P3R recipe for Arsene is incorrect

### ISSUE THREAD

**Issue by necessary3vil** [aqiu384/megaten-fusion-tool#183]
Arsene is listed a a persona you can fuse via dyad, but actually it can only be done via special fusion of Tam Lin, Jack-o'-Lantern and Neko Shogun.

**Comment by aqiu384** [comment]
Fixed with [8aa87af](https://github.com/aqiu384/megaten-fusion-tool/commit/8aa87af1a5ce6ae0e833f7cbec7404f27b201d80)
