### ISSUE TITLE
Persona 3 Reload Skill Inheritance

### ISSUE THREAD

**Issue by Groggerz** [aqiu384/megaten-fusion-tool#185]
Many of the what each persona inherits are incorrect (list screen where you can filter by level, arcana etc), for example it says Pisaca inherits ice elemental moves when he does not learn any except dark/curse. I understand its early so that may be the case as to why they may be wrong but thought to address it just in case. Love this page, I used it to see which persona I would use for a specific typing next in previous games.

**Comment by aqiu384** [comment]
Innate skill sets are not strictly correlated with inheritance types in P3R. Here, Pisaca has the exact same inherit type as Belphegor.
