### ISSUE TITLE
Almighty Amp not listed in Skill List for Persona 3 Reload

### ISSUE THREAD

**Issue by DebeshMishra** [aqiu384/megaten-fusion-tool#186]
So I was under the impression that Almighty Amp didn't exist in this game because the Skill List didn't list it. But today I fused Houou and inherited Arms Master which mutated into Almighty Amp. This took me by surprise. I have attached the image as proof.

![PXL_20240210_213914383](https://github.com/aqiu384/megaten-fusion-tool/assets/98782809/fbf1483b-7c92-4115-a5b2-6fbec2b7e48c)

**Comment by aqiu384** [comment]
Fixed with d50fc5c
