### ISSUE TITLE
Needs a legend, or explanation

### ISSUE THREAD

**Issue by echoes185** [aqiu384/megaten-fusion-tool#188]
I really want to use your charts but I want to know some features of it. Like you have rows highlighted green or red with zero indication on what that means. All the symbols are already familiar but it would still help to have a legend for everything. I assume the "The how to use" link is supposed to tell us but it doesn't bring me anywhere. All you have is data sources.

**Comment by aqiu384** [comment]
See https://aqiu384.github.io/megaten-database/how-to-use#general
