### ISSUE TITLE
Certain Non-inheiritance Skills Mutation P3 Reload

### ISSUE THREAD

**Issue by Mich0429** [aqiu384/megaten-fusion-tool#193]
The picture explains it all. The calculator lists Heaven's Blade as a non-inheritable move and yet I have it on Odin through mutation. If this is a well known thing that mutation ignores inheritance moves or not so forgive me if this is redundant. 
![20240220_010402](https://github.com/aqiu384/megaten-fusion-tool/assets/160573790/524bccbe-aaeb-486d-a397-b95170842373)

**Comment by aqiu384** [comment]
Fixed with 9f12e1e
