### ISSUE TITLE
[P3R] Inheritance mixup

### ISSUE THREAD

**Issue by rhoot** [aqiu384/megaten-fusion-tool#198]
Using the recipe generator for Persona 3 Reload, if you select Priestess/Parvati as the target, and add rec/Samarecarm from Dominion, as well as rec/Me Patra from Clotho, the fusions listed for the left chain are:

```
    Dominion x Orpheus = Narcissus
    Narcissus x Clotho [Samarecarm (42), Me Patra (39)] = Seiryu
    Seiryu x Clotho [Samarecarm (42), Me Patra (39)] = Cu Chulainn
    Cu Chulainn x Slime = Kaguya
    Kaguya x Mitra = Sarasvati
```

Note how it chose to use Samarecarm from Clotho instead of from Dominion, despite me selecting Dominion. By itself that wouldn't have been a huge issue since Dominion was used to fuse the Narcissus that is then fused with Clotho...

... except Narcissus also cannot inherit Samarecarm. So the fuse for Narcissus makes absolutely no difference in this fusion chain.

**Comment by aqiu384** [comment]
Fixed with a965bef
