### ISSUE TITLE
[P3R] Wrong ingredient level on Ziodyne

### ISSUE THREAD

**Issue by rhoot** [aqiu384/megaten-fusion-tool#199]
In the P3R fusion calculator, if you select ele/Ziodyne, Thunderbird (35) is the top selection for ingredient. But Thunderbird doesn't learn Ziodyne until level 39.

![image](https://github.com/aqiu384/megaten-fusion-tool/assets/1258798/abd369cf-6165-463c-9214-ee9bc904fad4)

**Comment by aqiu384** [comment]
Fixed with a965bef
