### ISSUE TITLE
[BUG] [Soul Hackers] Some Entity and Zealot fusion results are one rank off

### ISSUE THREAD

**Issue by Gravitinox** [aqiu384/megaten-fusion-tool#2]
The Entity and Zealot fusion formula is slightly different from normal fusions. For both 2-demon and 3-demon fusions that results in Entity and Zealot it is simply the average of the demons' levels (all decimals are ignored) [[source: a Japanese wiki](http://bmky.net/data/sh/system/unite/god.html), I also tested it in the game with the following examples] I'm guessing the code may be treating it as a normal fusion and adding an extra 3 levels?

Example A, the tool shows Lvl 61 Entity Ometeotl = Lady Diana (52) + Tyrant Loki (59). However, the result is actually one rank lower, Lvl 55 Entity Black Maria `(52+59)/2 = 55.5`.

Example B, the tool shows Lvl 52 Zealot Aramisaki = Megami Scathach (36) + Vile Mishaguji (35). The result is actually one rank lower, Lvl 37 Zealot Ogun `(35+36)/2 = 35.5`.

**Comment by Gravitinox** [comment]
Sorry, I misread the wiki. ONLY 2-demon fusions do not add 3 levels at the end, 3-demon fusions still do. I've attached photos of the ingame fusion results.

Vile Mishaguji (35) + Megami Scathach (36) = Lvl 37 Zealot Ogun `(35+36)/2 = 35.5`
![sentity double bug 1](https://user-images.githubusercontent.com/33763879/39562385-070b5be4-4ede-11e8-8e03-c500db0c8675.jpg)

Lady Diana (52) + Tyrant Loki (59) = Lvl 55 Entity Black Maria `(52+59)/2 = 55.5`
![sentity double bug 2](https://user-images.githubusercontent.com/33763879/39562386-07334d70-4ede-11e8-8056-408847fea4eb.jpg)

Tyrant Balor (48) + Deity Osiris (59) + Lady Diana (52) = Entity Ometeotl (61) `(48+59+52)/3 = 53` But the result isn't Lvl 55 Entity Black Maria, so the formula does add at least 3 levels.
![sentity triple bug](https://user-images.githubusercontent.com/33763879/39562388-07605bbc-4ede-11e8-93b7-2aeb69fcbddf.jpg)

**Comment by aqiu384** [comment]
Verified the three examples. Fixed with 2f9a5ab
