### ISSUE TITLE
[BUG][SMTIII]Different Skill for Mou-Ryo

### ISSUE THREAD

**Issue by newby24** [aqiu384/megaten-fusion-tool#20]
Demon **Mou-Ryo** learns **Mana Aid** at level 10, not _Mana Refill_ as stated in the tool:

![Mou-Ryo](https://user-images.githubusercontent.com/36610110/55183120-782e8a80-518f-11e9-956c-97a4b6fe1096.jpg)

Skill _Stun Needle_ on the screenshot **was morphed from** **Toxic Sting**, therefore it is _not a bug_!

**Mou-Ryo's base stats and skills (recruit)**:
![Mou-Ryo-base-recruit](https://user-images.githubusercontent.com/36610110/55183962-49191880-5191-11e9-8035-adf41af40de1.jpg)

**Comment by aqiu384** [comment]
Fixed with 4051d56
