### ISSUE TITLE
Fusion Calculator Recommends Uninheritable Skills

### ISSUE THREAD

**Issue by SenpaiMeow** [aqiu384/megaten-fusion-tool#202]
Hello, I was attempting to use the Fusion Calculator to create a 6 element Loki and part of the left path recommendation is:

    Cybele [Spell Master (73)] x Robin Hood [Kougaon (41), Eigaon (42)] = Belphegor
    Belphegor x Anat = Loki A

I do not believe Belphegor can inherit Light skills which would mean the final Loki would not have the Kougaon spell. I was able to get around it this time with a Skill Card though wanted to at least report the calculator recommendation error.

**Comment by aqiu384** [comment]
Please provide a screenshot of the entire page.
