### ISSUE TITLE
Wrong power about myraid truth in p5r

### ISSUE THREAD

**Issue by awfahslerigu** [aqiu384/megaten-fusion-tool#205]
The power of myraid truth was recorded as root 360. But as I have some tests, neither take it as a single power nor take it as a whole power is wrong number(Compared with Megidolaon, which is recorded as root 210 power, the single power would lower than megidolaon definitly when same effects and enemies.) I guess it's a misunderstanding about root numbers, the correct power should be root 120, so the whole power should be root 1080 (equal with 3 times of root 1080).

**Comment by awfahslerigu** [comment]
oh dear I type wrong,root 1080 is equal with 3 times of root 120 lol

**Comment by aqiu384** [comment]
Fixed with 20d0366
