### ISSUE TITLE
Persona 3 Reload Qitian Dasheng + Barong Wrong Fusion

### ISSUE THREAD

**Issue by msnnf-iscteiul** [aqiu384/megaten-fusion-tool#209]
In Persona 3 Reload "Qitian Dasheng + Barong" does not result in "Atavaka" ingame, it results in "Kali".
![kali](https://github.com/aqiu384/megaten-fusion-tool/assets/56412586/fb551115-3ccd-40fc-84bf-e94b75b769d6)

**Comment by aqiu384** [comment]
Fusion Settings > Uncheck "Atavaka"
