### ISSUE TITLE
SMT5V Dawn of Demise description is inaccurate

### ISSUE THREAD

**Issue by CTOBN** [aqiu384/megaten-fusion-tool#215]
Currently it reads
`Ally normal attack crit rate x1.3 + Pierce`
However, I know from using Cheat Engine to view the value when attacking with Cu Chulainn Rampage (Dawn of Demise was placed in Nahobino's innate slot, the other demons were Vritra and Nue) that the crit rate multiplier applies to skills too, so it'd be more accurate to say something like
`Ally crit rate x1.3 + ally normal attacks Pierce`

**Comment by aqiu384** [comment]
Fixed with c8b3271
