### ISSUE TITLE
Typo for the SMTV Vengeance Calculator

### ISSUE THREAD

**Issue by EnriqueBenny** [aqiu384/megaten-fusion-tool#219]
Just a small typo, I assume this is the place to post it. This is for the SMTVV page, specifically the Aogami Type-0 Essence that is currently listed at level 8. The Level 8 Aogami Essence is "Aogami Type-1," listing Aramasa and Rakunda as the skills. Thanks for your hard work! It's the best fusion calculator out there.

**Comment by EnriqueBenny** [comment]
Same issue with the Aogami type at level 17. It's listed as Aogami Type-2, not Type-1.

**Comment by aqiu384** [comment]
Fixed with 3213001
