### ISSUE TITLE
adding alignment for SMT 1?

### ISSUE THREAD

**Issue by ix** [aqiu384/megaten-fusion-tool#22]
hi,

the early smt games rely on alignment a lot, namely being that you can't summon demons opposite of your alignment; hence i'd like to know what alignment the demons which i'm fusing are

however, this data isn't displayed for SMT 1 (nor for 2 or if... but i haven't played them so i don't know if alignment holds the same significance)

it's displayed for strange journey so i don't know if this is just a lack of data or it just not being there

**Comment by aqiu384** [comment]
Fixed with e00fe29
