### ISSUE TITLE
Unable to use some calculators

### ISSUE THREAD

**Issue by EthanHumphrey** [aqiu384/megaten-fusion-tool#222]
I've been using this site for a while (really great work by the way!) for both P5R and more recently P3R. However, I'm no longer able to access either of those calculators as the pages both just show a YouTube link and nothing else. Some of the other calculators seem to load. I've tried refreshing, opening a private tab, and clearing my website data and cache to no avail.

**Comment by aqiu384** [comment]
Fixed with a4a647c
