### ISSUE TITLE
CHART IS SO FUCKING WRONG IT MAKE YOU LOOK RETARDED 

### ISSUE THREAD

**Issue by ImTheeGod** [aqiu384/megaten-fusion-tool#224]
SINCE THIS GAME CAME OUT AND I TRIED TO USE THIS "FUSION CHART AND GUIDE" IT'S GIVEN ME NOTHING BUT THE WRONG FUCKING FUSION RESULTS FUCKING MAKING YOURSELF LOOK RETARDED ONLINE DON'T HELP YOU!!

**Comment by Matternik** [comment]
what

**Comment by ImTheeGod** [comment]
Fusion CART and persona MATERIAL AND RESULTS are fucking wrong as fuck dead ass did you even take the time to try all the persona fusions
