### ISSUE TITLE
Incorrect Persona Trait Descriptions

### ISSUE THREAD

**Issue by Meme-Templar** [aqiu384/megaten-fusion-tool#229]
Ardha's persona trait "Naranari" says "HP restore x2" when it should say "SP restore x2"
Johanna's persona trait "Gaia Blessing" should say "Ally Burn + Freeze + Shock affliction rate +50%". It is currently incorrectly copied from "Gaia Pact".
(For Persona 5 Royal BTW, not that persona traits exist anywhere else)

**Comment by aqiu384** [comment]
Fixed with 4734dd6
