### ISSUE TITLE
Soul Hackers 3DS Mitama and Elements + Chagrin and Seiten Taisei

### ISSUE THREAD

**Issue by Matternik** [aqiu384/megaten-fusion-tool#230]
Currently playing Soul Hackers on 3DS and I noticed that the fusions listed for the Mitama with the Elements are almost all wrong.

Ara Mitama isn't "Gnome + any other Element" but rather "Salamander + any other Element"

Nigi Mitama can't be crafted with Salamander but is "Any Element + any other Element except Salamander"

Kusi Mitama can't be crafted with a normal fusion but requires a triple fusion. I coudn’t find any definitive criteria for the result so I’ll just write here every possible combination.
“Gnome + Salamander + Sylph N”
“Gnome + Salamander + Sylph”
“Gnome + Undine + Sylph N”
“Gnome + Undine + Sylph”
“Gnome + Sylph N + Sylph”
“Undine + Sylph N + Sylph”

Saki Mitama can't be crafted with a normal fusion but requires a triple fusion. Again, I couldn’t find a criteria so here’s every possible combination.
“Gnome + Salamander + Undine”
“Salamander + Undine + Sylph N”
“Salamander + Undine + Sylph”
“Salamander + Sylph N + Sylph”

Also, "Chagrin" is misspelled in the description for the skill “Escape” as “Chaglin”.

Also also, "Seiten Taisei" doesn't appear by that name in this game but rather as "Wu Kong", but I'm not sure if this one was intentional since it's been called countless of different ways through the games.

Still, thank you so much for this tool. Been using it for years and couldn't imagine completing any compendium without it.
(シ_ _)シ

**Comment by aqiu384** [comment]
Fixed with a4a647c
