### ISSUE TITLE
Persona 3 Reload: Incorrect Values for Critical Buffs

### ISSUE THREAD

**Issue by KosmicLupus** [aqiu384/megaten-fusion-tool#231]
The Crit Rate Boost, Crit Rate Amp, Rebellion and Revolution values are incorrect

The Calculator Says:
- Crit Rate Boost (x1.05 Critical Rate)
- Crit Rate Amp (x1.15 Critical Rate)
- Rebellion (x1.07 Critical Rate)
- Revolution (x1.15 Critical Rate)

In actuality, all of these Increases are Additive not Multiplicative:
- Crit Rate Boost = Flat +5% Critical Rate Increase
- Crit Rate Amp = Flat +15% Critical Rate Increase
- Rebellion = Flat +7% Critical Rate Increase
- Revolution = Flat +15% Critical Rate Increase
(E.g if you were using Brave Blade which has a 20% Crit Rate and casted Rebellion on yourself, it would be 27% Crit Rate)

Also might be of note:
- Crit Rate Amp will override Crit Rate Boost 
- Rebellion and Revolution do stack

If someone would like a Source these are Reload Databases composed by CantThinkOfBetterName (Dataminer and Tester, "ctobn" on Discord)
- [Reload Database](https://docs.google.com/spreadsheets/d/1f4Bhkg0gBqUSm4YR1Bba1JsQn6w6fPDrqBTaWlHla8A/edit?usp=sharing)
- [Episode Aigis Database](https://docs.google.com/spreadsheets/d/1BZA_ce8oyDApezEoDW0mYeV6okerur6WPaIX9RXdeWs/edit?usp=sharing)

**Comment by aqiu384** [comment]
Fixed with 77a991d
