### ISSUE TITLE
I think the P3R Mothman recipe list is inaccurate 

### ISSUE THREAD

**Issue by BeelzebubsWarden** [aqiu384/megaten-fusion-tool#235]
I was trying to do a handful of the recipes but they weren’t making mothman. Maybe I’m being stupid but the low level Narcissus and Queen Medb recipes weren’t resulting in mothman. I’m too dumb/impatient to play this game without a guide so any help is appreciated. 
![image](https://github.com/user-attachments/assets/60243a24-5fb1-4d56-9797-79991875a871)

**Comment by aqiu384** [comment]
Check special fusion condition.
