### ISSUE TITLE
SMT5V Skill Description/Availability Updates

### ISSUE THREAD

**Issue by CTOBN** [aqiu384/megaten-fusion-tool#236]
There's a couple small things I think could be worth updating on SMT5V's skill descriptions

Inaccuracies/Missing Effects:
- Dekajaon: Also resets "natural immunity" (the effect where characters become more resistant to ailments the more times they are afflicted with said ailment).
- Omagatoki: Conserve - I recognize that all the Fiends are recognized as Dark - Neutral internally, however a special property is enforced for Fiends that causes their alignment to be "Unknown", much like the Nahobino's alignment. As a result no Fiends (including Alice) should learn Omagatoki: Conserve. It's intrinsic to being a Fiend, so if you changed a non-Fiend demon's race to Fiend and changed nothing else this would apply too.
- Auspicious Beast - The effect actually sets the demon's skill potential to the max value of all demons with Auspicious Beast in the active party. For example, if you had both Baihu and Zhuque out, they would both have +2 Phys/+5 Fire/+0 Ice/+5 Elec/+0 Force/+1 Ailment/+1 Support. Switching in Qing Long to the 3rd demon slot would update Ice to +2 and Force to +5, and use that new potential set for all 3 while they are all out.
- Four Heavenly Kings - It actually applies the effect to the demon switching in if an ally with Four Heavenly Kings is in the active party while switching in. The effect is not applied to the demon that was already in the active party.
- Kept Waiting - It's 25% HP and 15% MP, not 25 HP and 15 MP.
- Trickery - The 1.3x multiplier is itself multiplied by the number of allies with Trickery. This means that 2 allies with Trickery gives a 2.6x multiplier. Hypothetically 3 Trickery allies would mean 3.9x, but 3 Trickery allies can't be combined with an innate skill affected by Trickery.

Missing Numbers:
- Omagatoki: Hit - Multiplier is 2.5x for both accuracy and ailments. Also applies after the accuracy soft-cap and Mirage, making it the only way to achieve more than 50% accuracy while afflicted with Mirage, and also meaning that it turns 40% accuracy into 100% accuracy, whereas normally a 2.5x accuracy multiplier would turn 40% accuracy into about 99.03% accuracy.
- Omagatoki: Doubler - Precise effect is 3.3x to the change produced by the buff/debuff. For example, +2 Attack is normally 1.4x, or (1 + 0.4)x. With Omagatoki: Doubler it becomes (1 + 0.4 x 3.3)x, or 2.32x. -2 Accuracy is normally 0.85x, or (1 - 0.15)x. With Omagatoki: Doubler it becomes (1 - 0.15 x 3.3)x, or 0.505x. Only applies to effects on the character with Doubler active, and not to enemies that character attacks. Additionally, due to a bug, the Defense stage is treated as though it was its inverse (for example, instead of -1 Defense meaning you go from 1.2x without Doubler to 1.66x with Doubler, it actually means you go from 1.2x without Doubler to 0.67x with Doubler (this interaction comes up when triggering counters). This bug only applies to Defense stages, and not Attack, Accuracy, or Evasion.
- Omagatoki: Luck - Effect is 2x EXP and 4x Macca
- Magatsuhi Thriftiness: The precise effect is "While deployed, if a Magatsuhi skill is used, recover 8-15% Magatsuhi after use". Additionally, if you determine that updating the "Filling the Magatsuhi Gauge" section of the "Help" page would be worthwhile, Skillful Conservation uses the exact same range, so it would be "Skillful Conservation (Minimum)" = 8% and "Skillful Conservation (Maximum)" = 15% (also for that section, Vengeful Opportunist has been nerfed to 2% and Vengeance has been nerfed to 15%).

Inaccurate by Technicality:
- Helmsman: It would be more accurate to say "Next ally accuracy x1.35 and chance of them correctly targeting under Mirage x1.36", since reducing the odds of mis-targeting from 50% to 32.5% actually means reducing it from 50% to 32% after truncation, and 68% to correctly target is 50% x 1.36.

Missing Nuance (Not strictly needed to have an accurate description, but may be worth including if that can be done within a small enough text body):
- Bowl of Hygieia - 125% max HP restore is applied with a MAX(a, b) function comparing it to the skill's natural overheal amount. In effect that means that it only applies for skills that heal to 100% max HP, or that the skill's max healing is raised to 125% max HP if it was lower.
- Omagatoki: Critical - It also applies to skills that scale off level. This is notable because no other effect that would allow magic to crit (such as Fickle Personality, for example) is capable of applying to level-based skills, and Omagatoki: Critical is the only possible way to get a level-based skill to crit at all.
- Critical Zealot - The x0.9 side of it does not apply for level-based skills. So it might be more accuracy to say "Dmg dealt x0.9 with St-based and Ma-based skills, also crit dmg dealt x1.45"
- Boon Boost/Boon Boost EX - Does not apply if the -kaja/-kunda effect comes from an innate skill.
- Heavenly Reversal - Does not refresh the timer on said "-kaja and -kunda" effects
- Angelic Order - Worth noting that "actions" in this case excludes Pass, Swap, and Dismiss. Additionally, it might be worth noting that this applies after paying a Magatsuhi skill's cost.
- Spirited Synergy - Not on Endure's once per battle, or any once per battle.
- Summer Dream - Not on Enduring Soul's once per battle, or any once per battle.
- Sacrificial Proxy - Not on Enduring Soul's once per battle, or any once per battle.
- Divine Dismantlement - Might be more accurate to add ", and removes effects incapacitated ally did not have", since it will remove effects the incapacitated ally didn't have. For example, if Nahobino uses Luminescent Mirage, then Divine Dismantlement triggers, Nahobino will lose Luminescent Mirage even if there is no <element> Block/Tetrakarn/Makarakarn effect being copied.
- Servant of God: Worth noting that "actions" in this case excludes Pass, Swap, and Dismiss
- Herkeios: May be worth adding ", including guests"
- Avenger: May be worth adding ", including guests"
- <element> Gestalt skills: Since negative skill potentials exist, a ", x1 min" may be worth adding.
- Scarlet Blade: Worth noting that, unlike all other innate skills that mention "effects", Scarlet Blade counts ailments as an effect. Also potentially worth noting that "Omagatoki" only counts as 1 effect regardless of how many Omagatoki effects apply concurrently.
- Capricious Goddess: Worth noting that "actions" in this case excludes Pass (but does not exclude Swap and Dismiss).
- Hammer of Judgment: Worth noting that the "-kunda" effect must be received during the enemy's turn for it to count (unless Heavenly Counter triggers it, that interaction hasn't been tested).

**Comment by aqiu384** [comment]
Fixed with 05583f7

**Comment by CTOBN** [comment]
A couple revisions after seeing the update
- Doubler was 3.3x, not 3.4x
- Angelic Order and Servant of God **ex**clude Swap/Dismiss/Pass
- I checked again to be sure, Hammer of Judgment is also triggered by a repelled Fang Breaker, so it just has to be a skill.

**Comment by aqiu384** [comment]
Fixed with 8b2026d
