### ISSUE TITLE
P5R / Incorrect Crit Rate Buffs

### ISSUE THREAD

**Issue by KosmicLupus** [aqiu384/megaten-fusion-tool#238]
I made a similar post about Reload but wanted to to done for Royal too
All of these Values were found from the [Persona Modding Server](https://discord.gg/HYxcgaAB) when looking at the Code

- Rebellion is a Flat +7% Crit Rate Increase
- Revolution is a Flat +15% Crit Rate Increase and Stacks with Rebellion
- Brave Step applies Rebellion to All Allies

- Apt Pupil is x1.5 Base Crit Rate
- Fortified Moxy is x1.25 Base Crit Rate
- Adverse Resolve is x1.25 Base Crit Rate
- Trigger Happy is x1.25 Base Crit Rate

**Comment by aqiu384** [comment]
Fixed with 8fd7ee6
