### ISSUE TITLE
SMT IV Incorrect Demon and Skill Data + Request

### ISSUE THREAD

**Issue by Matternik** [aqiu384/megaten-fusion-tool#239]
Noticed a few errors while using the tool for SMT IV

**Regarding demons:**
Both Gaea Man and Gaea Woman resist Gun and Dark instead of repelling them

(Minor typo) Corpses name should be Corpse

The fiends that null all ailments (i.e. Chemtrail, Trumpeter and Mother Harlot) have "25% resistances" noted. Shouldn’t they not have a percentage at all (since the immunity)?
Both Alice and Alilat null all ailments but do not have the same problem.

**Regarding skills:**
The description for Desperate Hit doesn’t mention that it’s a Str and Dex based skill; it's powered up by charge and every individual hit can crit, as with physical skills

Draconic Reaction doesn’t have the same effect as Beastly Reaction but boosts accuracy and evasion by two stages instead
 
Serpent of Sheol doesn’t just drain HP but also MP

Fallen Grace doesn’t target all foes but just 1 foe

Tetrabreak and Makarabreak names are instead Tetracoerce and Makaracoerce in this game

Additionally, this is not an error but a feature request.
Could something be added to differentiate which skill cannot be inherited through normal fusion and which skills cannot be whispered to Flynn?
These two types don’t always overlap and there’s no way to know with the tool.

e.g.
Kannuki-Throw cannot be inherited through normal fusion and cannot be whispered to Flynn.
Die for Me! cannot be inherited through normal fusion but can be whispered to Flynn.
Pandemic Bomb can be inherited through normal fusion but cannot be whispered to Flynn.

Regardless, thanks again for the tool, it’s useful as ever.

**Comment by aqiu384** [comment]
Ailment resist chance and immunity flags are two separate bytes. Fiends have both 25% innate resistance on top of nullifying them. Whisper skill exceptions have been listed in the game's help section.

**Comment by aqiu384** [comment]
Fixed with 1fa4bfc
