### ISSUE TITLE
Soul Hackers Skill Inheritance

### ISSUE THREAD

**Issue by nuclearunicorn7** [aqiu384/megaten-fusion-tool#24]
I don't know if this was intentional or if something has broken somewhere, but I distinctly remember that inherited skills were listed in a demon's entry for soul hackers and they aren't any more. The reason this concerns me is that unlike the other games in the series where the inheritance symbols can easily convey what's transferred, SH's categories aren't as immediately obvious. This could also be fixed by having a section that acts as a key or listing a skill's inheritance groups in the skill list. I'd just like the convenience of not having to go to a completely different resource to figure out what's in each group.

**Comment by aqiu384** [comment]
Fixed with a9fa13a
