### ISSUE TITLE
Fusion Table Questions

### ISSUE THREAD

**Issue by LastChalice** [aqiu384/megaten-fusion-tool#25]
Hello Aqui348. 
Just have a few comments on your PQ2 fusion table.
When I tried to a fuse a lvl 13 Yatagarasu (Death) and Lvl 12 Chimera (Chariot) into a Jack Frost (magician), I instead received a lvl 17 Bicorn; this is contrary to your table, which says death and chariot are supposed to result in a magician persona instead of temperance.
The same happened with other personas -- Korpokur (5, star) and Orobas (9, magician) resulted in Yatagarsu when it should've resulted in a fool (i was guessing Bifrons), and an Orobas (magician, lvl 9) with an Archangel (lvl 14, justice) which should've become a fool results in a Power (lvl 18, justice). 
Is this an issue with gameplay progression (wild card lvl16, just before Kamoshida boss fight, 
 an error with the table, or am I reading the table wrong?
Thanks in advance.

**Comment by aqiu384** [comment]
The top-right half of the chart is for normal fusions, while the bottom-left is for triple fusions. Therefore [Death] x [Chariot] = Magician and [Star] x [Magician] = Fool during triple fusions, while Death x Chariot = Temperance and Star x Magician = Death during normal fusions as per chart readings.
