### ISSUE TITLE
Multiple Persona Q2 Sudama triple-reverse fusions don't work

### ISSUE THREAD

**Issue by Crossark** [aqiu384/megaten-fusion-tool#26]
I have actually yet to find a listed triple recipe for Sudama that does work; they all fuse Andras. My guess is that the triple-reverse fusions aren't properly taking into account the DLC personas selected in settings, since for the double-reverse fusion I do see a working recipe calling for Andras and Kaguya.

**Comment by aqiu384** [comment]
Fixed with 8aa7f9f
