### ISSUE TITLE
Devil Summoner: Soul Hackers alignments

### ISSUE THREAD

**Issue by ralsei** [aqiu384/megaten-fusion-tool#28]
pretty much the same issue as I opened for SMT1.
they matter in this game. if you could highlight them like SMT1 or SJ that'd be convenient.

**Comment by aqiu384** [comment]
Fixed with 18d7be1

**Comment by ralsei** [comment]
if possible, soul hackers also has "extremely chaos" and "extremely law" alignments; while MC doesn't have alignment, it basically serves so that if you summon EC you can only summon C/N but no Law, and vice versa for EL; and if you have N/L/C in your party you can't summon extremely anything

it'd be nice to include this data

**Comment by aqiu384** [comment]
Fixed with 87bb87f
