### ISSUE TITLE
[BUG] [Soul Hackers] Some races are missing forward fusions

### ISSUE THREAD

**Issue by Gravitinox** [aqiu384/megaten-fusion-tool#3]
Enigma, Entity, Zealot, Reaper and UMA are all missing forward fusions. They are actually fusable and appear to be treated as another race for fusion purposes (with some exceptions as noted below). Here is one example using Entity Black Maria, results are same as if it was a Diety:
![entity 5](https://user-images.githubusercontent.com/33763879/39664675-2829f4c0-50b9-11e8-89ad-6678001606b2.jpg)

Another example using Reaper Chernobog, results are same as if it was a Vile:
![reaper 3](https://user-images.githubusercontent.com/33763879/39664702-c0409142-50b9-11e8-9170-f2d9ff411753.jpg)

One last example using UMA Kuda, same as Beast with two exceptions noted below:
![uma 5](https://user-images.githubusercontent.com/33763879/39664763-cca930fa-50ba-11e8-96d6-56ca577454cf.jpg)

I've checked this ingame by going through all 2-demon combinations with these 5 races, and can confirm that:
-Firstly, none of the 5 races can be fused with Elemental to rank up/down, this seems to be the case for 3-demon fusions with 2 Elementals also.
For non-Elemental race fusions:
-Enigma, Entity and Zealot, all results are same as Diety.
-Reaper, all results are same as Vile.
-UMA, all results are same as Beast, except they cannot be fused with Beast or UMA as shown in the example above.
*All tests are done while it's not New or Full Moon.

I've attached a zip file with the ingame shots of all Enigma, Reaper and UMA fusion combinations. You can look through them to double-check.
[shots.zip](https://github.com/aqiu384/megaten-fusion-tool/files/1976783/shots.zip)

**Comment by aqiu384** [comment]
Verified provided examples. Fixed with b89b2d5
