### ISSUE TITLE
Persona 5 Fixes

### ISSUE THREAD

**Issue by ChucklesTheJester** [aqiu384/megaten-fusion-tool#31]
Hello, i like using your tool, however the fusions with treasure demons are incorrect, as the the outcome is based by the other person’s current level, not base level, also, the persona outcome for max confidants will give you a different persona if it’s not maxed, is there a way to add a level calculator to more accurately give results as well as confidant settings for if it is maxed out?
Aside from that, considering the sources used, could it be possible to add a negotiation tab as well?

**Comment by aqiu384** [comment]
> is there a way to add a level calculator
How do you envision setting the individual levels for all possible ingredient personas only when necessary?
> could it be possible to add a negotiation tab as well?
Needs a link for a data source providing a comprehensive list of all negotiation questions and answers.

**Comment by ChucklesTheJester** [comment]
Hm, for the first one, when you click on a persona and view forward fusions, maybe there can be a drop down to select the persona’s level?
as for the link, http://spwiki.net/persona5/wikis/768.html it’s all in japanese, but the links can take you to each persona’s info, and to their responses and if the response will be good, bad, or neutral, it might take some time to compare the translations to the english text that appears ingame

**Comment by aqiu384** [comment]
After playing through P5 JP the negotiation data source appears to have many inaccuracies. Closing until a better guide can be found.
