### ISSUE TITLE
PQ2 QR Generator Question

### ISSUE THREAD

**Issue by Revan410** [aqiu384/megaten-fusion-tool#32]
Not really an issue...I just had 2 questions:
1: Is there any way that you could possibly add unique persona abilities (such as Fool Card, Empress Pierce, etc.) to the Persona Q2 QR generator so we could add them to sub-personas?
2: Is there any way we can donate to a PayPal or something?  I use your tools a lot and appreciate all the work put in.

**Comment by aqiu384** [comment]
1. Party-unique skills cannot be added to sub-persona QR codes. They are reported as invalid when scanned.
2. Your gratitude is appreciated. However, I cannot accept donations stemming from this particular project.
