### ISSUE TITLE
Devil Survivor Overclocked Missing Demons

### ISSUE THREAD

**Issue by Koolzo** [aqiu384/megaten-fusion-tool#34]
The Devil Survivor Overclocked seems to be missing a whole lot of demons in the level 60+ range. It almost looks like it's just the base Devil Survivor game fusions, and the base Devil Survivor page appears to be missing, which I'd guess is the problem.

EDIT: Skills outdated, too. Almost certainly has been reverted to the old Devil Survivor page, not the updated Overclocked.

**Comment by aqiu384** [comment]
Fixed with cdb7f1e
