### ISSUE TITLE
[SMT III]Fusion Chart Problem

### ISSUE THREAD

**Issue by ErmineKamo** [aqiu384/megaten-fusion-tool#35]
According to the Heretic Mansion and other[ Fusion Tables](https://gamefaqs.gamespot.com/ps2/582958-shin-megami-tensei-nocturne/map/2000?raw=1), the resultant race from the normal fusion Dragon x Holy should be Snake instead of Tyrant.

**Comment by aqiu384** [comment]
Fixed with 67f196a
