### ISSUE TITLE
Adding precise numbers to skill power in SMT 3?

### ISSUE THREAD

**Issue by Minaly22** [aqiu384/megaten-fusion-tool#37]
I am greatly thankful for the fusion tool and the skill list, however I have been wondering why damaging skills are only roughly categorized with 'Weak, Medium, Heavy, Severe' damage when it could have been possible to categorize them by the numbers of their skill power.

Here is a japanese site that has a list of the numbers labeled under "威力" (lit. 'Power') and I think it could be great to add the information somehow, although I am not sure how to add it without jarring the current aesthetics of the skill list too much. 

http://ifs.nog.cc/fool-est.hp.infoseek.co.jp/shin_dds3/data/skill_1.html
http://ifs.nog.cc/fool-est.hp.infoseek.co.jp/shin_dds3/data/skill_2.html
http://ifs.nog.cc/fool-est.hp.infoseek.co.jp/shin_dds3/data/skill_3.html
http://ifs.nog.cc/fool-est.hp.infoseek.co.jp/shin_dds3/data/skill_4.html

Sadly there are some skills that still don't have the numbers, such as Life Drain, and basically all of Demi-fiend's physical skills.

(you can hit me with a message if you have trouble with the japanese name for the skills, I will be happy to help, although I just checked with google translate changing the whole site into English and it works for 95% of the information so far)

**Comment by aqiu384** [comment]
Fixed with 3bd8954
