### ISSUE TITLE
[Persona 5 Royal] Shadow List Improvements

### ISSUE THREAD

**Issue by pokeguru87** [aqiu384/megaten-fusion-tool#38]
I would like to suggest a few Shadow List improvements. The ability to sort by Appears column would greatly appreciated. Also, and this could apply to other pages, the ability to filter by a column. Personally I'd really want the appears column, but if it could be done in a way for any column, that would be perfect. Either of these would make it much easier to ensure I get all shadows in a palace or, heck just make it more manageable to find the data that is applicable to the situation I am in.

**Comment by aqiu384** [comment]
Sorting by level should group appearances closer together.
