### ISSUE TITLE
Strange Journey Redux incompatibilities

### ISSUE THREAD

**Issue by SuperOkazaki** [aqiu384/megaten-fusion-tool#4]
Hi,

It looks like the Strange Journey Redux password generator is not working. 99% of the time, the password, when entered in the game, is said to be invalid. 

This code
`kAYYggwgZkggAuZ4
SQEgSadgghex5AfO`
works in the generator and in SJ:R but all others I have tried do not.

Entering in a SJ:R code into the generator does not work, and entering a generator code into the game does not work either. I'm not sure what the differences between the original and the remake are, but since there is a listing for the remake on the page, support is being planned?

EDIT: I'm playing the English NTSC-U version

**Comment by SuperOkazaki** [comment]
I figured out some more details and "cracked the code" of the issue. It seems that the skill "bytes" of the password are off in SJ:R. Like I said above, the code above works, but not exactly how it appears in the generator.

Below, I've attached two examples of passwords in the generator, that when entered in verbatim in the game, cause a skill mismatch. 
![example1](https://user-images.githubusercontent.com/12318905/39952872-0af48d98-556e-11e8-81f4-baf064a8aae5.png)
![example2](https://user-images.githubusercontent.com/12318905/39952899-74d21a46-556e-11e8-9c74-0b85f5859c93.png)


To me, it seems like the skill IDs are off and as a result the password is failing the validation check by the game. Coincidentally, it seems that the one I tried is a valid password, just with different skills.

I hope this info will help you! If you need any more experimentation done, let me know.

**Comment by aqiu384** [comment]
Please test the following passwords and report back the resultant skills:
1. `fEOFBAG+CVydn5xn 0vKh0sSAwwSX9oT-`
2. `fEP+BAG+E+ydn5xn 0vKh0sSAwwSX9oVu`
3. `Rn8EVFLyQhfxSAay XwHVdn%gZLnyJ8n4`
4. `Rn8EVFLyOhfxSAay XwHVd-%gZLnyJ8mB`
5. `ycLbzEnb9Mr8RK3y eDEE6FubRBztZsKD`
6. `ycLbzDnb9MrDRK3y eDEE6FubRBztZsK4`
7. `+LoAOhnMoRTxD+ks +86vodTc5REwVxo$`
8. `+Lo5eho-oRTxDxos +87ymtTc5REwVxmV`
9. `sihiwtvVRF%QGK6C $PBBc57N%Cefnq5n`
10. `sihiwtvVRF%wGK6C $PBBc57N%Cejnq6L`

**Comment by SuperOkazaki** [comment]
All of them are marked invalid.

[Here is an album showing you, so you can verify I entered them as requested.](https://imgur.com/a/dHXncaa)

**Comment by aqiu384** [comment]
The odd-numbered passwords were taken from screenshots of the original Strange Journey. If you are correct about the skill codes being altered from the original game, a lot of the old passwords may no longer be valid. Try finding older passwords online and check if any of them still work. If most of them are broken, we will need sample passwords from Redux to rebuild the skill tables.

**Comment by SuperOkazaki** [comment]
[Here is an album with 5 demons from the game, and their respective passwords.](https://imgur.com/a/GaRF76I)
I cannot find a single other SJ password online that still works.

**Comment by aqiu384** [comment]
The issue turned out to be the encoding scheme rather than the underlying skill table. Fixed with  272f122
