### ISSUE TITLE
[P5R] Will of the Sword & Johanna Skills

### ISSUE THREAD

**Issue by RozalinGaming** [aqiu384/megaten-fusion-tool#42]
Futsunushi's Will of the Sword description is currently incorrect.
It currently reads: Charge skills +200% damage instead, Begins battle with Concentrate.
But it should actually be: Charge and Concentrate effect boosted to +200%; with a note about gaining Concentrate at the start of battle being a bug.

Johanna has Makajama as an innate ability but it's not listed on the Persona page.

**Comment by aqiu384** [comment]
Fixed with 35256df
