### ISSUE TITLE
Persona 5 Royal Lachesis-Regent Fusion Issue

### ISSUE THREAD

**Issue by CelestialYakumo** [aqiu384/megaten-fusion-tool#44]
Hello! I'm trying to fuse for Atropos in game and I looked to your chart for fusion possibilities. I tried seeing if Lachesis and Regent made it like it says on the chart, however in my game it says it makes Ariadne Picaro? I'm not sure if it's a mistake on my part though so I'm hoping for some help with this.

**Comment by aqiu384** [comment]
Treasure demons rank up and down based on the current persona level, no the base level.
