### ISSUE TITLE
[SMT IV] Incorrect reverse fusions for demons who are the highest level normal fusion in their race but not the highest overall.

### ISSUE THREAD

**Issue by StormFever** [aqiu384/megaten-fusion-tool#45]
If the average level of the two component demons is higher than every normal fusable demon in the resulting race but lower than some of the special fusable demons your tool assumes that the fusion will default to the highest level normal fusable demon. However in reality those fusions are invalid and the game actually won't let you fuse those demons.

Examples:
Barbatos (Fallen 76) + Pendragon (Snake 66) = Dragon 71+
The next highest Dragon over 71 is Koga Saburo which can't be normal summoned and there's no Dragon higher that can be normal summoned so this fusion is invalid. However the page for the highest dragon lower than 71 (Quetzalcoatl) lists this as a valid recipe.

Shive (Fury 90) + Taraka (Femme 56) = Lady 73+
The only Lady higher than this level is Xi Wangmu which can only be special summoned so this fusion is invalid. However once again the page for the Skadi lists this as a vaild recipe.

Obviously this only applies to races where the highest level demon can't be normal fused. Otherwise fusions like these will default to the highest level demon of that race as expected.

**Comment by aqiu384** [comment]
Fixed with 5e2fb1a
