### ISSUE TITLE
P5R - Missing Forward/Backwards Fusion for Izanagi-no-Okami

### ISSUE THREAD

**Issue by KeeltheSwift** [aqiu384/megaten-fusion-tool#46]
Given that InO is supposed to be only fusable via Advanced Fusion, I'm not surprised you missed this, but I've discovered (by accident) that Fusing a lvl 80 InO with the Orichalcum (Faith treasure) can result in an InOP.
![P5R Treasure Demon and InO](https://user-images.githubusercontent.com/50393611/82272688-4fe08d00-9949-11ea-80d4-35e31a5c8398.jpg)

This also suggests then that the Fusion Chart is missing a row/column for fusing World with Treasure Demons.

**Comment by aqiu384** [comment]
Fixed with b2eddbe
