### ISSUE TITLE
Incorrect Data - Persona Q2

### ISSUE THREAD

**Issue by MissingNo29** [aqiu384/megaten-fusion-tool#47]
The Omnibane Doll shadow in Persona Q2 is weak to Fire, but it's incorrectly listed as a resistance.

As for the other elements, I have not tested all of them, but the data was correct for Bless and Psychic skills at the very least.

**Comment by MissingNo29** [comment]
As a side note, I have found this guide quite useful so far during for the several Persona games I have been playing through recently. Thank you for making this!

**Comment by aqiu384** [comment]
Enepedia data indicates Omnibane Doll is resistant to all magic.
