### ISSUE TITLE
Inaccurate values for Persona 3 skills

### ISSUE THREAD

**Issue by Phoenix-neat** [aqiu384/megaten-fusion-tool#52]
Howdy! I have no idea how to edit this/ if I can edit this but I saw an issue so... yeah.

Verified via Skills.tbl in P3FES

Agi/ Garu/ Bufu/ Zio do (40) damage

Hama/ Mudo have a 30% chance insta kill chance
Mahama/ Mamudo have a 25% insta kill chance
Hamaon/ Mudoon have 40% insta kill chance
Mahamaon/ Mamudoon have 35% insta kill chance
Samara/ Die For Me! have a 45% insta kill chance

Single target status moves: 40%
Multi target status moves: 35%
Pralaya: 50% ailment, 30% crit
Frolic is 30% self inflicted charm
Trickster is a 100% chance of all ailments
Dreamfest is an 80% charm chance

Vile Assault does (295) damage
Primal Force does (580) damage

There's probably more but these were the biggest differences

Healing values:
Dia (50)
Diarama (160)
Media (40)
Mediarama (140)

**Comment by aqiu384** [comment]
Fixed with 31522ea
