### ISSUE TITLE
SMT Nocturne Mou-Ryo has a wrong skill

### ISSUE THREAD

**Issue by Maisterthing** [aqiu384/megaten-fusion-tool#59]
By checking the wiki and testing in game I found out that Mou-Ryo **doesn't** have the Mana Refill skill (Regenerate SP while walking) like the fusion calculator says, instead he actually has the Mana Aid skill (Regenerate SP after combat). Just a tiny error I noticed.

**Comment by aqiu384** [comment]
Fixed with 637d71e
