### ISSUE TITLE
Problem with passwords in SJRedux

### ISSUE THREAD

**Issue by Neofranky** [aqiu384/megaten-fusion-tool#6]
I noticed that the password gen is bugged. I tried to make a Snake Vouvire and it gave me a Yurlungur (rank down Snake) instead. I thought it was an issue with ranks, but when I tried to make a Gui Xian (rank up snake) it gave me the correct demon. Some others I've talked to have gotten similar issues, like trying to make a neutral Fake Demonica, and getting a Law version instead.

**Comment by aqiu384** [comment]
Please provide a list of incorrect passwords and in-game outputs for verification.

**Comment by aqiu384** [comment]
Switched around Vouvire/Yurlungur and Demonica-L/Demonica-C codes. Fixed with 5995cfd
