### ISSUE TITLE
Search/Filter demons by ailments

### ISSUE THREAD

**Issue by MSalah73** [aqiu384/megaten-fusion-tool#63]
I know players generally don't look for ailments as a deciding factor for choosing demons, but it would be really helpful in deciding which demons to pick for some bosses with bothersome skills that have a high percentage of inflicting ailments.

**Comment by aqiu384** [comment]
https://aqiu384.github.io/megaten-fusion-tool/smt4/skills

**Comment by MSalah73** [comment]
This page shows the skills list. I meant the demons preset resistances to aliments.

**Comment by aqiu384** [comment]
Fixed with 39f9265
