### ISSUE TITLE
Persona Q2 Inheritance Type

### ISSUE THREAD

**Issue by uliminati** [aqiu384/megaten-fusion-tool#64]
I'm currently compiling data on skill inheritance for Persona Q2, since I couldn't find it anywhere else. The actual inheritance type, not the "Physical/Magic/Support/Defense" displayed ingame. When I'm done, are you interested in the list to add it to your tool?

**Comment by aqiu384** [comment]
Yes.

**Comment by uliminati** [comment]
Here's some data so far:

Types are "Physical", Fire, Ice, Elec, Wind, Psy, Nuke, Bless, Curse, "Recovery", "Navigation", Almighty
Types in "quotes" are names I chose myself because they are the most reasonable, but you can change/simplify what you like.
Most inheritance types are "obvious", i.e. Personas who naturally learn Agilao will often be Fire inheritance.

Fire, Ice, Elec, Wind, Psy, Nuke, Bless, Curse: do not inherit SP-based skills of the opposite element, but can inherit all HP-based skills. E.g. Psy inheritance does not inherit Freila, but can inherit Nucleostrike Link. Some personas have unusual inheritance, e.g. Seiryu learns Garula and Windstrike Link, but is actually Ice inheritance type (inherits Zionga but not Agilao).

"Physical": does not inherit Recovery and Almighty skills. This includes HP-based Almighty skills.

"Navigation"+Almighty: So far, all personas who learn exclusively Navigation skills can inherit all skills. DLC Personas can inherit all skills, so I called them Almighty. There is at least one special case "Apsaras" who also inherits all skills. It learns a Navigation skill, so I judged it to be Navigation type.

"Recovery": Does not inherit Physical skills, and does not learn HP-based elemental skills such as "Hientou" or "Psystrike Link". So far, I've only found "Kaiwan" to have this type (but I'm only at level ~40 right now).

All personas can inherit all Support, Ailment or Passive skills (so far).

It's possible I won't level up to 89 to be able to fuse all Personas, it depends on the length of the game
