### ISSUE TITLE
Fusion error

### ISSUE THREAD

**Issue by petitepirouette** [aqiu384/megaten-fusion-tool#7]
For Persona 5:
Kikuri-hime and Koh-i-noor do not make sarasvati (no DLC)
instead they fuse Skadi

**Comment by aqiu384** [comment]
Treasure Demons rank up and down based on the current level of the second ingredient. This tool assumes all ingredients start at their base levels. If Kikuri-Hime's level is 40-44, the result will be Sarasvati. Else if Kikuri-Hime's level is 45-49, the result will be Skadi.
