### ISSUE TITLE
P5S demon changes merciless

### ISSUE THREAD

**Issue by TheEnlightenedOne212** [aqiu384/megaten-fusion-tool#71]
Hi I noticed in P5S demons you encounter in jails have different weaknesses depending the difficulty.
For example a slime in hard will resist physical but on merciless they will null it instead. Another example is berith on hard will resist fire but on merciless it will be changed to drain and it gains a null wind. I'm sure there are a lot more demons as well(I can confirm your own demons from the compendium will not change) but I can't test fully at the moment until I clear the game again. Is there any chance these could be shown with a toggle or something else I can't think of?

Unrelated but salvation in P5S also resurrects party members.

**Comment by aqiu384** [comment]
Fixed with 2c96796
