### ISSUE TITLE
Mistake in P5S Yoshitsune Skill List

### ISSUE THREAD

**Issue by KeeltheSwift** [aqiu384/megaten-fusion-tool#72]
Yoshitsune naturally learns Knockdown Style at Level 84 in Persona 5 Strikers. Your skill list is missing it.
![Yoshitsune Learns Knockdown Style](https://user-images.githubusercontent.com/50393611/110843442-49bff200-8276-11eb-80f0-dfac7a5bcfa5.png)

**Comment by aqiu384** [comment]
Fixed with e1afe23
