### ISSUE TITLE
Gamelist gone

### ISSUE THREAD

**Issue by StriFe79** [aqiu384/megaten-fusion-tool#75]
You might've made a change to the tool, but normally there would be a list of games and if you click on it you'll be led to the demons and fusions of that game, but now you can only get there through such a way that it's a bit illogical :) Not sure if this was intended or not, but I still thought I'll make an issue about it just in case.

![aqiu384 fusion list](https://user-images.githubusercontent.com/42231383/112195976-d8375a80-8c0a-11eb-8e15-0912b1c35e59.png)

**Comment by aqiu384** [comment]
This was intentional.
