### ISSUE TITLE
Incorrect Norn Triple-Reverse Fusion in P3 FES: The Answer

### ISSUE THREAD

**Issue by Typhon1981** [aqiu384/megaten-fusion-tool#78]
[https://aqiu384.github.io/megaten-fusion-tool/p3aeg/personas/Norn/fissions/triple](url)

It says Jatayu + Attis + Titania will result in Norn, but it actually gives you Atropos.

For reference, my Attis is level 67, my Jatayu is 64, and my Titania is 59.

**Comment by Typhon1981** [comment]
Just fused Norn the traditional way and the innate skills listed are also wrong. Panta Rhei is not an innate skill.

**Comment by aqiu384** [comment]
Fixed with 34173f9
