### ISSUE TITLE
Wrong Normal Fusion formula for P4G (maybe also P4?)

### ISSUE THREAD

**Issue by REWesker** [aqiu384/megaten-fusion-tool#8]
There're number of wrong fusions recipes which have odd low sum of levels. For example, Valkyrie (8) + Ukobach (3) gives Forneus (6) and not Ippon-Datara (17) as fusion tool suggests.
![p_20180607_143759](https://user-images.githubusercontent.com/40020402/41085618-c9082f1c-6a61-11e8-9df0-40a1fd9d88be.jpg)
There's such problem with any fusion that has sum of levels odd and low enough to actually give previous Persona in arcana list.

**Comment by aqiu384** [comment]
Confirmed Strange Journey, IV, and Apocalypse are the only games that round up fusion result levels. Fixed with 0d5f274
