### ISSUE TITLE
SMT 3: Pyro Jack + Taraka creates Pisaca, not Chatterskull

### ISSUE THREAD

**Issue by officegossip** [aqiu384/megaten-fusion-tool#83]
Just invested some gems to get an Aquans to create a Pyro Jack to fuse with my Taraka to create a Chatterskull but the result is a Pisaca not a Chatterskull, is there a way to fix this on the tool? This isn’t the first time I’ve come across an error on the website.

**Comment by aqiu384** [comment]
Fixed with 52cf3f7
