### ISSUE TITLE
Alice demon missing from Demon List in Megami Ibunroku Persona Fusion Calculator

### ISSUE THREAD

**Issue by JJ2670** [aqiu384/megaten-fusion-tool#85]
I see every demon on this list except for Alice who's a Fiend, is level 99, has both 999 HP and SP, resists every element except Hieroglyphein, cannot be negotiated with, must be fought, drops Pagan Idol and is found in Deva Yuga, Avidya World and the last level in Mikage Ruins.

**Comment by aqiu384** [comment]
Fixed with 58ef066
