### ISSUE TITLE
Some demons are missing in the Shin Megami Tensei IV Calculator

### ISSUE THREAD

**Issue by LOuroboros** [aqiu384/megaten-fusion-tool#86]
Title.
Asterius *(Asterios in Japan)* is one of the DLC demons. It's a golden palette swap of Minotaur that can be obtained by fusing Tyrant Morax, Wilder Raiju *(who in the tool is called "Raijuu" btw)* and Fallen Halphas.

**EDIT**: Pic.
![Untitled6079](https://user-images.githubusercontent.com/4485172/123116093-00577500-d417-11eb-8b32-8492dff02a02.png)

I ctrl+f'd "aster" in the tool, and the only single match was Master Therion, to further clarify.

**EDIT2**: Uriel and Raphael are missing too. Their recipe is unlocked after defeating them in the Clipped Wings 1 DLC.

**Comment by aqiu384** [comment]
Enable DLC demons under Fusion Settings tab.

**Comment by LOuroboros** [comment]
> 
> 
> Enable DLC demons under Fusion Settings tab.

Huh. Okay then.

Why are they there instead of just being enabled by default though? I'm curious. It's kinda unintuitive, specially when the tool displays unfusable demons such as the hordes, the mitama, et cetera.
