### ISSUE TITLE
Missing DLC skills in the skill list of IVA

### ISSUE THREAD

**Issue by LOuroboros** [aqiu384/megaten-fusion-tool#88]
Title.
[The skill list of SMT IV Apocalypse's calc](https://aqiu384.github.io/megaten-fusion-tool/smt4f/skills) seems to be missing the data of certain skills such as Demifiend's Freikugel or Gaea Rage, or Guardian's Eye. Skills that can be obtained by using cheats.

I wanted to check the data of Freikugel in this game out of curiosity and thought that, since the calc contains a list presenting the game's skills that also includes normally unobtainable skills, it would have that one too.

**Comment by aqiu384** [comment]
Fixed with 4a011e1
