### ISSUE TITLE
P4G Triple Fusions missing

### ISSUE THREAD

**Issue by REWesker** [aqiu384/megaten-fusion-tool#9]
There're some triple fusions missing, for example Hua Po (25) + Eligor (12) + Sandman (5) = Pyro Jack (32)

![p_20180611_193508](https://user-images.githubusercontent.com/40020402/41232018-28aaa8dc-6daf-11e8-9298-d19797a2f921.jpg)

The cause seems to be that if triple fusion results in a persona that was used as a fusion ingrident it should give next persona in a list.

**Comment by aqiu384** [comment]
Verified provided test case. Fixed with 832ed3b
