### ISSUE TITLE
SMT 3: Bicorn x Ame no Uzume creates Baphomet, NOT Fomorian

### ISSUE THREAD

**Issue by Jwguy** [aqiu384/megaten-fusion-tool#91]
Title.

Ran into this while trying to fuse a Daisoujou. =P

**Comment by Jwguy** [comment]
Found out that Bicorn x Flaemis is also incorrect. It currently lists that it creates Zhen, when it actually creates Raiju. Does SMT3 Remaster have a different forward fusion table?

**Comment by aqiu384** [comment]
Settings > Toggle Cursed Fusion
