### ISSUE TITLE
Hecatoncheires with wrong natural affinity in P5R ?

### ISSUE THREAD

**Issue by IceTMDAbss** [aqiu384/megaten-fusion-tool#94]
I just randomly simulated a fusion based on Jatayu + Crystal Skull that gives Hecatoncheires.

The site mentions that Heca's natural affinity is Physical, however, in my simulation he can inherit any skill move but _Mafreidyne_, which leads me to believe that **his natural affinity is Psychic rather than Physical** despite him learning exclusively Physical moves.

**Comment by aqiu384** [comment]
Fixed with 8f6af95
