### ISSUE TITLE
Question: Setting up a fork

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [aqiu384/megaten-fusion-tool#96]
I'm setting up a fork of this repository to add Persona 4 Golden with modded personas, how do i set up github pages properly?

**Comment by TheDrawingCoder-Gamer** [comment]
I'm able to fully setup angular and run `ng serve -o` but idk how you set up github pages with you setup

**Comment by aqiu384** [comment]
`ng build --prod --aot --base-href /megaten-fusion-tool/`

**Comment by TheDrawingCoder-Gamer** [comment]
this causes the assets images not to work, am i doing smth wrong?

**Comment by aqiu384** [comment]
`cd docker && ./update-assets-subpath.sh`
