### ISSUE TITLE
Strange Journey Redux fusions

### ISSUE THREAD

**Issue by Sothe01** [aqiu384/megaten-fusion-tool#97]
Some of the fusions seem to be shifted. I was trying to fuse a Kwancha but all the combinations I tried gave me a Tsuchigumo, which is the Jirae demon right above, and the fusions for Tsuchinoko gave me a Titan, the Jirae demon above... I don't know how many are shifted, if it's only a few or more than the Jirae demons.

**Comment by Sothe01** [comment]
Tsuchigumo* instead of Tsuchinoko but the point stands.

**Comment by aqiu384** [comment]
Turn off your Lapalce and Paracelsus subapps.
