### ISSUE TITLE
[P5S] Incorrect elemental resistances for personas of magic mains

### ISSUE THREAD

**Issue by personality-finder** [aqiu384/megaten-fusion-tool#99]
The elemental resistances for Zorro, Carmen, and Johanna in P5S are similar to those of their second-awakening personas.
Zorro: Nul Wind, Str Bless, Wk Elec
Carmen: Nul Fire, Str Elec, Wk Ice
Johanna: Nul Nuke, Str Curse, Wk Psy

**Comment by aqiu384** [comment]
Fixed with 5d31266
